description: 'Somatic alterations in genome.'
raw:
  bqrtsv:
    description: 'Base quality recalibration metrics.'
    pattern: "\\.sage\\.bqr\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'alt'
          type: 'char'
        - field: 'ref'
          type: 'char'
        - field: 'trinucleotideContext'
          type: 'char'
        - field: 'count'
          type: 'float'
        - field: 'originalQual'
          type: 'float'
        - field: 'recalibratedQual'
          type: 'float'
  genecvg:
    description: 'Gene coverage metrics.'
    pattern: "\\.sage\\.gene\\.coverage\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'gene'
          type: 'char'
        - field: 'chromosome'
          type: 'char'
        - field: 'posStart'
          type: 'float'
        - field: 'posEnd'
          type: 'float'
        - field: 'missedVariantLikelihood'
          type: 'float'
        - field: 'DR_0'
          type: 'float'
        - field: 'DR_1'
          type: 'float'
        - field: 'DR_2'
          type: 'float'
        - field: 'DR_3'
          type: 'float'
        - field: 'DR_4'
          type: 'float'
        - field: 'DR_5'
          type: 'float'
        - field: 'DR_6'
          type: 'float'
        - field: 'DR_7'
          type: 'float'
        - field: 'DR_8'
          type: 'float'
        - field: 'DR_9'
          type: 'float'
        - field: 'DR_10'
          type: 'float'
        - field: 'DR_11'
          type: 'float'
        - field: 'DR_12'
          type: 'float'
        - field: 'DR_13'
          type: 'float'
        - field: 'DR_14'
          type: 'float'
        - field: 'DR_15'
          type: 'float'
        - field: 'DR_16'
          type: 'float'
        - field: 'DR_17'
          type: 'float'
        - field: 'DR_18'
          type: 'float'
        - field: 'DR_19'
          type: 'float'
        - field: 'DR_20'
          type: 'float'
        - field: 'DR_21'
          type: 'float'
        - field: 'DR_22'
          type: 'float'
        - field: 'DR_23'
          type: 'float'
        - field: 'DR_24'
          type: 'float'
        - field: 'DR_25'
          type: 'float'
        - field: 'DR_26'
          type: 'float'
        - field: 'DR_27'
          type: 'float'
        - field: 'DR_28'
          type: 'float'
        - field: 'DR_29'
          type: 'float'
        - field: 'DR_30_39'
          type: 'float'
        - field: 'DR_40_49'
          type: 'float'
        - field: 'DR_50_59'
          type: 'float'
        - field: 'DR_60_69'
          type: 'float'
        - field: 'DR_70_79'
          type: 'float'
        - field: 'DR_80_89'
          type: 'float'
        - field: 'DR_90_99'
          type: 'float'
        - field: 'DR_100_149'
          type: 'float'
        - field: 'DR_150_199'
          type: 'float'
        - field: 'DR_200_249'
          type: 'float'
        - field: 'DR_250_299'
          type: 'float'
        - field: 'DR_300_349'
          type: 'float'
        - field: 'DR_350_399'
          type: 'float'
        - field: 'DR_400_449'
          type: 'float'
        - field: 'DR_450_499'
          type: 'float'
        - field: 'DR_500_599'
          type: 'float'
        - field: 'DR_600_699'
          type: 'float'
        - field: 'DR_700_799'
          type: 'float'
        - field: 'DR_800_899'
          type: 'float'
        - field: 'DR_900_999'
          type: 'float'
        - field: 'DR_1000_1099'
          type: 'float'
        - field: 'DR_1100_1199'
          type: 'float'
        - field: 'DR_1200_1299'
          type: 'float'
        - field: 'DR_1300_1399'
          type: 'float'
        - field: 'DR_1400_1499'
          type: 'float'
        - field: 'DR_1500_1599'
          type: 'float'
        - field: 'DR_1600_1699'
          type: 'float'
        - field: 'DR_1700_1799'
          type: 'float'
        - field: 'DR_1800_1899'
          type: 'float'
        - field: 'DR_1900_1999'
          type: 'float'
        - field: 'DR_2000_2999'
          type: 'float'
        - field: 'DR_3000_3999'
          type: 'float'
        - field: 'DR_4000_4999'
          type: 'float'
        - field: 'DR_5000_5999'
          type: 'float'
        - field: 'DR_6000_6999'
          type: 'float'
        - field: 'DR_7000_7999'
          type: 'float'
        - field: 'DR_8000_8999'
          type: 'float'
        - field: 'DR_9000_9999'
          type: 'float'
        - field: 'DR_10000'
          type: 'float'
  exoncvg:
    description: 'Exon coverage metrics.'
    pattern: "\\.sage\\.exon\\.medians\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'gene'
          type: 'char'
        - field: 'chromosome'
          type: 'char'
        - field: 'posStart'
          type: 'float'
        - field: 'posEnd'
          type: 'float'
        - field: 'exonRank'
          type: 'float'
        - field: 'medianDepth'
          type: 'float'
