description: 'Neoepitope prediction.'
raw:
  neocand:
    description: 'Neoepitope candidates.'
    pattern: "\\.neo\\.neo_data\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'NeId'
          type: 'float'
        - field: 'VariantType'
          type: 'char'
        - field: 'VariantInfo'
          type: 'char'
        - field: 'VariantCopyNumber'
          type: 'float'
        - field: 'CopyNumber'
          type: 'float'
        - field: 'SubclonalLikelihood'
          type: 'float'
        - field: 'GeneIdUp'
          type: 'char'
        - field: 'GeneIdDown'
          type: 'char'
        - field: 'GeneNameUp'
          type: 'char'
        - field: 'GeneNameDown'
          type: 'char'
        - field: 'ChrUp'
          type: 'char'
        - field: 'ChrDown'
          type: 'char'
        - field: 'OrientUp'
          type: 'float'
        - field: 'OrientDown'
          type: 'float'
        - field: 'UpstreamAA'
          type: 'char'
        - field: 'DownstreamAA'
          type: 'char'
        - field: 'NovelAA'
          type: 'char'
        - field: 'NmdMin'
          type: 'float'
        - field: 'NmdMax'
          type: 'float'
        - field: 'CodingBasesLengthMin'
          type: 'float'
        - field: 'CodingBasesLengthMax'
          type: 'float'
        - field: 'FusedIntronLength'
          type: 'float'
        - field: 'SkippedDonors'
          type: 'float'
        - field: 'SkippedAcceptors'
          type: 'float'
        - field: 'UpTranscripts'
          type: 'char'
        - field: 'DownTranscripts'
          type: 'char'
        - field: 'WildtypeAA'
          type: 'char'
        - field: 'CodingBaseUpPosStart'
          type: 'float'
        - field: 'CodingBaseUpPosEnd'
          type: 'float'
        - field: 'CodingBasesUp'
          type: 'char'
        - field: 'CodingBaseCigarUp'
          type: 'char'
        - field: 'CodingBaseDownPosStart'
          type: 'float'
        - field: 'CodingBaseDownPosEnd'
          type: 'float'
        - field: 'CodingBasesDown'
          type: 'char'
        - field: 'CodingBaseCigarDown'
          type: 'char'
  neopred:
    description: 'Neoepitope predictions.'
    pattern: "\\.neo\\.neoepitope\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'NeId'
          type: 'float'
        - field: 'VariantType'
          type: 'char'
        - field: 'VariantInfo'
          type: 'char'
        - field: 'GeneName'
          type: 'char'
        - field: 'UpAminoAcids'
          type: 'char'
        - field: 'NovelAminoAcids'
          type: 'char'
        - field: 'DownAminoAcids'
          type: 'char'
        - field: 'PeptideCount'
          type: 'float'
        - field: 'TpmSource'
          type: 'char'
        - field: 'RnaFrags'
          type: 'float'
        - field: 'RnaDepth'
          type: 'float'
        - field: 'TpmUp'
          type: 'float'
        - field: 'TpmDown'
          type: 'float'
        - field: 'ExpectedTpm'
          type: 'float'
        - field: 'RawEffectiveTpm'
          type: 'float'
        - field: 'EffectiveTpm'
          type: 'float'
        - field: 'TpmCancerUp'
          type: 'float'
        - field: 'TpmCancerDown'
          type: 'float'
        - field: 'TpmPanCancerUp'
          type: 'float'
        - field: 'TpmPanCancerDown'
          type: 'float'
        - field: 'NmdMin'
          type: 'float'
        - field: 'NmdMax'
          type: 'float'
        - field: 'CodingBasesLengthMin'
          type: 'float'
        - field: 'CodingBasesLengthMax'
          type: 'float'
        - field: 'FusedIntronLength'
          type: 'float'
        - field: 'SkippedDonors'
          type: 'float'
        - field: 'SkippedAcceptors'
          type: 'float'
        - field: 'TranscriptsUp'
          type: 'char'
        - field: 'TranscriptsDown'
          type: 'char'
        - field: 'VariantCopyNumber'
          type: 'float'
        - field: 'CopyNumber'
          type: 'float'
        - field: 'SubclonalLikelihood'
          type: 'float'
