tidy:
  candidates:
    description: 'Neoepitope candidates.'
    schema:
      latest:
        tbl1:
          - field: 'ne_id'
            type: 'int'
            description: 'Unique ID for neoepitope'
          - field: 'variant_type'
            type: 'char'
            description: 'MISSENSE, INFRAME, OUT_OF_FRAME_FUSION, INFRAME_FUSION, FRAMESHIFT'
          - field: 'variant_info'
            type: 'char'
            description: 'Unique identifier for variant. For point mutations: [chr]:[pos]:[ref]:[alt]; For SV: [chrUp]:[posUp]:[orientUp]-[chrDown]:[posDown]:[orientDown]'
          - field: 'variant_cn'
            type: 'float'
            description: 'Allele copies of the point mutation or structural variant'
          - field: 'cn'
            type: 'float'
            description: 'Total chromosomal copies at variant location'
          - field: 'subclonal_likelihood'
            type: 'float'
            description: 'Subclonal likelihood of variant (for point mutations only)'
          - field: 'gene_id_up'
            type: 'char'
            description: 'Ensembl gene ID for upstream gene'
          - field: 'gene_id_down'
            type: 'char'
            description: 'Ensembl gene ID for downstream gene'
          - field: 'gene_name_up'
            type: 'char'
            description: 'Gene name for upstream gene'
          - field: 'gene_name_down'
            type: 'char'
            description: 'Gene name for downstream gene'
          - field: 'chr_up'
            type: 'char'
            description: 'Chromosome for upstream gene'
          - field: 'chr_down'
            type: 'char'
            description: 'Chromosome for downstream gene'
          - field: 'orient_up'
            type: 'float'
            description: 'Orientation for upstream gene'
          - field: 'orient_down'
            type: 'float'
            description: 'Orientation for downstream gene'
          - field: 'aa_upstream'
            type: 'char'
            description: 'Upstream AA'
          - field: 'aa_downstream'
            type: 'char'
            description: 'Downstream AA'
          - field: 'aa_novel'
            type: 'char'
            description: 'Novel AA'
          - field: 'nmd_min'
            type: 'float'
            description: 'Smallest # of coding bases from stop codon to exon splice junction across all downstream transcripts'
          - field: 'nmd_max'
            type: 'float'
            description: 'Largest # of coding bases from stop codon to exon splice junction across all downstream transcripts'
          - field: 'coding_bases_length_min'
            type: 'float'
            description: '# of coding bases for shortest fused transcript combination (not presently used)'
          - field: 'coding_bases_length_max'
            type: 'float'
            description: '# of coding bases for longest fused transcript combination (not presently used)'
          - field: 'fused_intron_length'
            type: 'float'
            description: 'Length of fused Intron (not presently used)'
          - field: 'skipped_donors'
            type: 'float'
            description: '# of splice donors skipped in transcripts other than those in the fusion transcripts'
          - field: 'skipped_acceptors'
            type: 'float'
            description: '# of splice acceptors skipped in transcripts other than those in the fusion transcripts'
          - field: 'transcripts_up'
            type: 'char'
            description: 'List of transcripts in the up gene that support the neoepitope'
          - field: 'transcripts_down'
            type: 'char'
            description: 'All unique transcripts on the up gene that support the neoepitope'
          - field: 'aa_wildtype'
            type: 'char'
            description: 'Wildtype AA sequence (for point mutations only)'
          - field: 'coding_base_up_pos_start'
            type: 'float'
            description: 'Start position of coding bases in upstream transcript'
          - field: 'coding_base_up_pos_end'
            type: 'float'
            description: 'End position of coding bases in upstream transcript'
          - field: 'coding_bases_up'
            type: 'char'
            description: 'Coding bases in upstream transcript'
          - field: 'coding_base_cigar_up'
            type: 'char'
            description: 'CIGAR string for coding bases in upstream transcript'
          - field: 'coding_base_down_pos_start'
            type: 'float'
            description: 'Start position of coding bases in downstream transcript'
          - field: 'coding_base_down_pos_end'
            type: 'float'
            description: 'End position of coding bases in downstream transcript'
          - field: 'coding_bases_down'
            type: 'char'
            description: 'Coding bases in downstream transcript'
          - field: 'coding_base_cigar_down'
            type: 'char'
            description: 'CIGAR string for coding bases in downstream transcript'
  predictions:
    schema:
      latest:
        tbl1:
          - field: 'ne_id'
            type: 'int'
            description: 'Unique ID for neoepitope'
          - field: 'variant_type'
            type: 'char'
            description: 'MISSENSE, INFRAME, OUT_OF_FRAME_FUSION, INFRAME_FUSION, FRAMESHIFT'
          - field: 'variant_info'
            type: 'char'
            description: 'Unique identifier for variant. For point mutations: [chr]:[pos]:[ref]:[alt]; For SV: [chrUp]:[posUp]:[orientUp]-[chrDown]:[posDown]:[orientDown]'
          - field: 'gene_name'
            type: 'char'
            description: 'Gene name or fusion name for fusions'
          - field: 'aa_up'
            type: 'char'
            description: 'Section of the neoepitope that matches the upstream transcript'
          - field: 'aa_novel'
            type: 'char'
            description: 'Novel section of the neoepitope (if any)'
          - field: 'aa_down'
            type: 'char'
            description: 'Section of the neoepitope that matches the downstream transcript (if any)'
          - field: 'peptide_count'
            type: 'float'
            description: '# of novel peptides between 8 and 12 bases that form part of neoepitope'
          - field: 'tpm_source'
            type: 'char'
            description: 'Sample, CancerType or Cohort'
          - field: 'rna_frags'
            type: 'float'
            description: '# of fragments supporting the novel RNA sequence'
          - field: 'rna_depth'
            type: 'float'
            description: 'Total RNA coverage at the last base of the upstream AA sequence'
          - field: 'tpm_up'
            type: 'float'
            description: 'Sum of estimated TPM across all transcripts that support the predicted upstream AA sequence'
          - field: 'tpm_down'
            type: 'float'
            description: 'Sum of estimated TPM across all transcripts that support the predicted downstream AA sequence'
          - field: 'tpm_expected'
            type: 'float'
            description: 'Estimated TPM of the neo-epitope'
          - field: 'tpm_raw_effective'
            type: 'float'
            description: 'TPM estimate from direct fragment count'
          - field: 'tpm_effective'
            type: 'float'
            description: 'CombinedTPM estimate from direct fragment count and transcript expression'
          - field: 'tpm_cancer_up'
            type: 'float'
            description: 'SUM Median TPM for up transcripts for cancer type'
          - field: 'tpm_cancer_down'
            type: 'float'
            description: 'SUM Median TPM for down transcripts for cancer type'
          - field: 'tpm_pancancer_up'
            type: 'float'
            description: 'SUM Median TPM for up transcripts pan-cancer'
          - field: 'tpm_pancancer_down'
            type: 'float'
            description: 'SUM Median TPM for down transcripts pan-cancer'
          - field: 'nmd_min'
            type: 'float'
            description: 'Smallest # of coding bases from stop codon to exon splice junction across all downstream transcripts'
          - field: 'nmd_max'
            type: 'float'
            description: 'Largest # of coding bases from stop codon to exon splice junction across all downstream transcripts'
          - field: 'coding_bases_length_min'
            type: 'float'
            description: '# of coding bases for shortest fused transcript combination (not presently used)'
          - field: 'coding_bases_length_max'
            type: 'float'
            description: '# of coding bases for longest fused transcript combination (not presently used)'
          - field: 'fused_intron_length'
            type: 'float'
            description: 'Length of fused Intron (not presently used)'
          - field: 'skipped_donors'
            type: 'float'
            description: '# of splice donors skipped in transcripts other than those in the fusion transcripts'
          - field: 'skipped_acceptors'
            type: 'float'
            description: '# of splice acceptors skipped in transcripts other than those in the fusion transcripts'
          - field: 'transcripts_up'
            type: 'char'
            description: 'List of transcripts in the up gene that support the neoepitope'
          - field: 'transcripts_down'
            type: 'char'
            description: 'All unique transcripts on the up gene that support the neoepitope'
          - field: 'variant_cn'
            type: 'float'
            description: 'Allele copies of the point mutation or structural variant'
          - field: 'cn'
            type: 'float'
            description: 'Total chromosomal copies at variant location'
          - field: 'subclonal_likelihood'
            type: 'float'
            description: 'Subclonal likelihood of variant (for point mutations only)'

