description:
  'Determine germline HLA Class I types.'
raw:
  summary:
    description: 'Lilac summary.'
    pattern: "\\.lilac\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'Allele'
          type: 'char'
        - field: 'RefTotal'
          type: 'float'
        - field: 'RefUnique'
          type: 'float'
        - field: 'RefShared'
          type: 'float'
        - field: 'RefWild'
          type: 'float'
        - field: 'TumorTotal'
          type: 'float'
        - field: 'TumorUnique'
          type: 'float'
        - field: 'TumorShared'
          type: 'float'
        - field: 'TumorWild'
          type: 'float'
        - field: 'RnaTotal'
          type: 'float'
        - field: 'RnaUnique'
          type: 'float'
        - field: 'RnaShared'
          type: 'float'
        - field: 'RnaWild'
          type: 'float'
        - field: 'TumorCopyNumber'
          type: 'float'
        - field: 'SomaticMissense'
          type: 'float'
        - field: 'SomaticNonsenseOrFrameshift'
          type: 'float'
        - field: 'SomaticSplice'
          type: 'float'
        - field: 'SomaticSynonymous'
          type: 'float'
        - field: 'SomaticInframeIndel'
          type: 'float'
  qc:
    description: 'Lilac QC'
    pattern: "\\.lilac\\.qc\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'Status'
          type: 'char'
        - field: 'ScoreMargin'
          type: 'float'
        - field: 'NextSolutionAlleles'
          type: 'char'
        - field: 'MedianBaseQuality'
          type: 'float'
        - field: 'HlaYAllele'
          type: 'char'
        - field: 'DiscardedIndels'
          type: 'float'
        - field: 'DiscardedIndelMaxFrags'
          type: 'float'
        - field: 'DiscardedAlignmentFragments'
          type: 'float'
        - field: 'A_LowCoverageBases'
          type: 'float'
        - field: 'B_LowCoverageBases'
          type: 'float'
        - field: 'C_LowCoverageBases'
          type: 'float'
        - field: 'ATypes'
          type: 'float'
        - field: 'BTypes'
          type: 'float'
        - field: 'CTypes'
          type: 'float'
        - field: 'TotalFragments'
          type: 'float'
        - field: 'FittedFragments'
          type: 'float'
        - field: 'UnmatchedFragments'
          type: 'float'
        - field: 'UninformativeFragments'
          type: 'float'
        - field: 'HlaYFragments'
          type: 'float'
        - field: 'PercentUnique'
          type: 'float'
        - field: 'PercentShared'
          type: 'float'
        - field: 'PercentWildcard'
          type: 'float'
        - field: 'UnusedAminoAcids'
          type: 'float'
        - field: 'UnusedAminoAcidMaxFrags'
          type: 'float'
        - field: 'UnusedHaplotypes'
          type: 'float'
        - field: 'UnusedHaplotypeMaxFrags'
          type: 'float'
        - field: 'SomaticVariantsMatched'
          type: 'float'
        - field: 'SomaticVariantsUnmatched'
          type: 'float'
