version: "v0.0.1"
tidy:
  summary:
    description: 'Lilac solution summary.'
    schema:
      - field: 'allele'
        type: 'char'
        description: 'Allele ID'
      - field: 'ref_total'
        type: 'float'
        description: 'Total assigned fragments from reference BAM'
      - field: 'ref_unique'
        type: 'float'
        description: 'Fragments uniquely assigned to allele'
      - field: 'ref_shared'
        type: 'float'
        description: 'Fragments assigned to ref allele and others in this solution'
      - field: 'ref_wild'
        type: 'float'
        description: 'Fragments matched to a wildcard allele'
      - field: 'tumor_total'
        type: 'float'
        description: 'Total assigned fragments from tumor BAM'
      - field: 'tumor_unique'
        type: 'float'
        description: 'Fragments uniquely assigned to allele'
      - field: 'tumor_shared'
        type: 'float'
        description: 'Fragments assigned to allele and others in this solution'
      - field: 'tumor_wild'
        type: 'float'
        description: 'Fragments matched to a wildcard allele'
      - field: 'rna_total'
        type: 'float'
        description: 'Total assigned fragments from RNA BAM'
      - field: 'rna_unique'
        type: 'float'
        description: 'Fragments uniquely assigned to allele'
      - field: 'rna_shared'
        type: 'float'
        description: 'Fragments assigned to allele and others in this solution'
      - field: 'rna_wild'
        type: 'float'
        description: 'Fragments matched to a wildcard allele'
      - field: 'tumor_cn'
        type: 'float'
        description: 'Copy number from Tumor/Ref fragment ratio and Purple copy number'
      - field: 'somatic_missense'
        type: 'float'
        description: 'Matched missense variants'
      - field: 'somatic_nonsense_or_frameshift'
        type: 'float'
        description: 'Matched nonsense or frameshift variants'
      - field: 'somatic_splice'
        type: 'float'
        description: 'Matched splice variants'
      - field: 'somatic_synonymous'
        type: 'float'
        description: 'Matched synonymous variants'
      - field: 'somatic_inframe_indel'
        type: 'float'
        description: 'Matched inframe indels'
  qc:
    description: 'Lilac QC'
    schema:
      - field: 'status'
        type: 'char'
        description: 'Either PASS or 1 or more warnings'
      - field: 'score_margin'
        type: 'float'
        description: 'Difference in score to second-top solution'
      - field: 'next_solution_alleles'
        type: 'char'
        description: 'Allele difference in second-top solution'
      - field: 'median_base_quality'
        type: 'float'
        description: 'Median base quality across all coding bases from all fragments'
      - field: 'hla_y_allele'
        type: 'char'
        description: 'HLA-Y allele detected if present, else NONE'
      - field: 'discarded_indels'
        type: 'float'
        description: 'Discarded fragments due to unknown INDELs'
      - field: 'discarded_indel_max_frags'
        type: 'float'
        description: 'Maximum fragment support for an indel detected but not present in any known allele'
      - field: 'discarded_alignment_fragments'
        type: 'float'
        description: 'Fragments discarded because 1 read aligns more than 1000 bases from a HLA A,B or C gene'
      - field: 'a_low_coverage_bases'
        type: 'float'
        description: 'Number of bases with less than 15-depth coverage across all coding bases, also for B and C genes'
      - field: 'b_low_coverage_bases'
        type: 'float'
        description: 'Number of bases with less than 15-depth coverage across all coding bases, also for A and C genes'
      - field: 'c_low_coverage_bases'
        type: 'float'
        description: 'Number of bases with less than 15-depth coverage across all coding bases, also for A and B genes'
      - field: 'a_types'
        type: 'float'
        description: '# of distinct HLA-A alleles fitted (0,1 or 2)'
      - field: 'b_types'
        type: 'float'
        description: '# of distinct HLA-B alleles fitted (0,1 or 2)'
      - field: 'c_types'
        type: 'float'
        description: '# of distinct HLA-C alleles fitted (0,1 or 2)'
      - field: 'total_fragments'
        type: 'float'
        description: 'Total of fragments overlapping a coding base of HLA-A, HLA-B or HLA-C with MAPQ >=1'
      - field: 'fitted_fragments'
        type: 'float'
        description: 'Total fragments assigned to fitted alleles (ie. exact or wildcard match at every heterozygous location)'
      - field: 'unmatched_fragments'
        type: 'float'
        description: 'Fragment that do not match any allele exactly in solution at all heterozygous location (eg. due to sequencing error or mapping error)'
      - field: 'uninformative_fragments'
        type: 'float'
        description: 'Fragments that do not overlap any heterozygous location considered in evidence phase'
      - field: 'hla_y_fragments'
        type: 'float'
        description: 'Fragments excluded from fit due to allocation to assignment to HLA-Y'
      - field: 'percent_unique'
        type: 'float'
        description: 'Percentage of fitted fragments that are uniquely assigned to 1 allele'
      - field: 'percent_shared'
        type: 'float'
        description: 'Percentage of fitted fragments allocated across multiple alleles'
      - field: 'percent_wildcard'
        type: 'float'
        description: 'Percentage of fitted fragments uniquely assigned to wildcard regions'
      - field: 'unused_amino_acids'
        type: 'float'
        description: '# of amino acids detected with at least 3 fragments support but not present in final allele solution set (excluding PON filtered and regions overlapping wildcards in selected alleles)'
      - field: 'unused_amino_acid_max_frags'
        type: 'float'
        description: 'Maximum fragments support for an unmatched amino acid not present in the final allele solution set'
      - field: 'unused_haplotypes'
        type: 'float'
        description: '# of haplotypes phased with at least 3 fragments support but not present in final allele solution set (excluding PON filtered and regions overlapping wildcards in selected alleles)'
      - field: 'unused_haplotype_max_frags'
        type: 'float'
        description: 'Maximum support for an unmatched haplotype not present in final allele solution set'
      - field: 'somatic_variants_matched'
        type: 'float'
        description: 'Somatic variants supported by solution allele'
      - field: 'somatic_variants_unmatched'
        type: 'float'
        description: 'Somatic variants not supported by solution allele'

