description: 'Telomere characterisation.'
raw:
  breakend:
    description: 'Telomeric rearrangements.'
    pattern: "\\.teal\\.breakend\\.tsv\\.gz$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'chromosome'
        type: 'char'
      - field: 'position'
        type: 'float'
      - field: 'orientation'
        type: 'float'
      - field: 'cOrGRich'
        type: 'char'
      - field: 'filter'
        type: 'char'
      - field: 'inTumor'
        type: 'char'
      - field: 'inGermline'
        type: 'char'
      - field: 'distanceToTelomere'
        type: 'float'
      - field: 'maxTelomericLength'
        type: 'float'
      - field: 'maxAnchorLength'
        type: 'float'
      - field: 'tumorSRTelDPTel'
        type: 'float'
      - field: 'tumorSRTelDPNotTel'
        type: 'float'
      - field: 'tumorSRTelNoDP'
        type: 'float'
      - field: 'tumorSRNotTelDPTel'
        type: 'float'
      - field: 'tumorDPTelNoSR'
        type: 'float'
      - field: 'tumorTotalSupport'
        type: 'float'
      - field: 'tumorMAPQ'
        type: 'float'
      - field: 'germlineSRTelDPTel'
        type: 'float'
      - field: 'germlineSRTelDPNotTel'
        type: 'float'
      - field: 'germlineSRTelNoDP'
        type: 'float'
      - field: 'germlineSRNotTelDPTel'
        type: 'float'
      - field: 'germlineDPTelNoSR'
        type: 'float'
      - field: 'germlineTotalSupport'
        type: 'float'
      - field: 'germlineMAPQ'
        type: 'float'
  tellength:
    description: 'Telomeric length and content.'
    pattern: "\\.teal\\.tellength\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'sampleId'
        type: 'char'
      - field: 'type'
        type: 'char'
      - field: 'rawTelomereLength'
        type: 'float'
      - field: 'finalTelomereLength'
        type: 'float'
      - field: 'fullFragments'
        type: 'float'
      - field: 'cRichPartialFragments'
        type: 'float'
      - field: 'gRichPartialFragments'
        type: 'float'
      - field: 'totalTelomericReads'
        type: 'float'
      - field: 'purity'
        type: 'float'
      - field: 'ploidy'
        type: 'float'
      - field: 'duplicateProportion'
        type: 'float'
      - field: 'meanReadDepth'
        type: 'float'
      - field: 'gc50ReadDepth'
        type: 'float'
