---
title: "Summary"
lightbox:
  match: auto
  effect: fade
execute: 
  echo: false
---

```{r}
#| label: pkg_load
#| message: false
{
  use("here", "here")
  use("dplyr")
  use("tibble", "tibble") # needed for tbl print
}
# box_path <- system.file("website/boxbox", package = "tidywigits")
box_path <- here::here("inst/website/boxbox")
options(box.path = box_path)
box::use(
  wigits/plot[cat_plot],
  wigits/utils[get_data, unnest_data],
  ppl_qc = purple/qc
)
```

```{r}
#| label: data_setup
dat <- get_data()
```

```{r}
#| label: purple_plotprep
relpath <- "nogit/seqc100/purple/plot"
p <- dat$ppl_plots |>
  mutate(path = paste(relpath, .data$bname, sep = "/"))
```

## Circos

::: {layout-nrow=1}

```{r}
#| label: purple_plots_circos
#| results: asis
cat_plot(p, "circos_baf_ar", group = "ppl_circos")
cat_plot(p, "circos_snv_indel_cn_sv", group = "ppl_circos")
```

:::

## QC Summary

```{r}
#| label: purple_qc
#| classes: plain
d <- dat$data |>
  unnest_data("purple_qc", schemas_all = dat$schemas)
ppl_qc$gt_tab(d, dat$schemas)
```
