---
title: "PEACH"
execute: 
  echo: false
html-table-processing: none
---


```{r}
#| label: pkg_load
#| warning: false
#| message: false
{
  use("dplyr")
  use("tibble", "tibble")
  # box_path <- system.file("website/boxbox", package = "tidywigits")
  box_path <- here::here("inst/website/boxbox")
  options(box.path = box_path)
  box::use(
    wigits/utils[get_data, unnest_data],
    wigits/table[reactable_wrapdown],
  )
}
```

```{r}
#| label: data_setup
dat <- get_data()
tool <- "peach"
dat$data <- dat$data |>
  dplyr::filter(grepl(tool, .data$tool_parser))
dat$schemas <- dat$schemas |>
  dplyr::filter(.data$tool == {{ tool }})
```

## QC

```{r}
#| label: peach_qc
tbl_nm <- "peach_qc"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

## Variant events

```{r}
#| label: peach_events
tbl_nm <- "peach_events"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

## Variant events linked to gene

```{r}
#| label: peach_eventsg
tbl_nm <- "peach_eventsg"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

## Haplotypes (best)

```{r}
#| label: peach_hapbest
tbl_nm <- "peach_hapbest"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

## Haplotypes (all)

```{r}
#| label: peach_hapall
tbl_nm <- "peach_hapall"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
gt::gt(d$res)
```

::: {.callout-tip}
## TODO

- Format tables better
:::
