---
title: "PURPLE"
lightbox:
  match: auto
  effect: fade
  desc-position: right
execute: 
  echo: false
html-table-processing: none
---

```{r}
#| label: pkg_load
#| warning: false
#| message: false
{
  use("dplyr")
  use("tibble", "tibble") # needed for tbl print
}
# box_path <- system.file("website/boxbox", package = "tidywigits")
box_path <- here::here("inst/website/boxbox")
options(box.path = box_path)
box::use(
  wigits/plot[cat_plot],
  wigits/utils[get_data, unnest_data],
  wigits/table[reactable_wrapdown, gt_tab],
  ppl_purity = purple/purity,
  ppl_qc = purple/qc,
  ppl_utils = purple/utils
)
```

```{r}
#| label: data_setup
dat <- get_data()
```

## QC

```{r}
#| label: purple_qc
#| #classes: plain
#| layout-nrow: 1
tbl_nm <- "purple_qc"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
qc_tab <- ppl_qc$gt_tab(d, dat$schemas)

tbl_nm <- "purple_puritytsv"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
purity_tab <- ppl_purity$gt_tab(d, dat$schemas)
qc_tab
purity_tab
```


```{r}
#| label: purple_plotprep
relpath <- "nogit/seqc100/purple/plot"
p <- dat$ppl_plots |>
  mutate(path = paste(relpath, .data$bname, sep = "/"))
```

## Plots

::: {layout="[ [1,1,1], [1,1,1], [1] ]"}

```{r}
#| label: purple_plots_other
#| results: asis
cat_plot(p, "purity_range", group = "ppl_other")
cat_plot(p, "segment", group = "ppl_other")
cat_plot(p, "clonality", group = "ppl_other")
cat_plot(p, "cn_distro", group = "ppl_other")
cat_plot(p, "map_distro", group = "ppl_other")
cat_plot(p, "somatic_cnpdf", group = "ppl_other")
cat_plot(p, "rainfall", group = "ppl_other")
```

:::


```{r}
#| label: count_rows
#| eval: false
dat$data |>
  dplyr::select(tool_parser, tidy) |>
  tidyr::unnest(tidy) |>
  dplyr::mutate(nr = purrr::map_int(data, nrow)) |>
  dplyr::arrange(dplyr::desc(nr)) |>
  dplyr::filter(grepl("purple", tool_parser)) |>
  print(n = 30)
```


## Copy Number Alterations

::: {.panel-tabset .nav-pills}

### Genes

```{r}
#| label: purple_cnvgenetsv
#| column: screen-inset
tbl_nm <- "purple_cnvgenetsv"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
#  just keep a subset of genes for display
# https://raw.githubusercontent.com/umccr/gene_panels/v24.03.0/somatic_panel/3_final_panel/final_panel.tsv
genes <- system.file("website/boxbox/purple/genes.tsv", package = "tidywigits") |>
  readr::read_tsv(col_types = "c") |>
  dplyr::pull("gene_symbol")
d$res |>
  dplyr::filter(gene %in% genes) |>
  reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```

### Segments

```{r}
#| label: purple_cnvsomtsv
#| column: screen-inset
tbl_nm <- "purple_cnvsomtsv"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
d$res |>
  reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```

### Drivers

```{r}
#| label: purple_drivercatalog_prep
tbl_nm <- "purple_drivercatalog"
d <- dat$data
```

:::: {.panel-tabset .nav-pills}

#### Somatic

```{r}
#| label: purple_drivercatalog_somatic
#| column: screen-inset
d_som <- d |>
  ppl_utils$unnest_data_drivercatalog(schemas_all = dat$schemas, get_germline = FALSE)
d_som$res |>
  reactable_wrapdown(
    descriptions = d_som$schema$schema[c("field", "description")],
    id = paste0(tbl_nm, "_somatic"),
    pagination = TRUE
  )
```

#### Germline

```{r}
#| label: purple_drivercatalog_germline
#| column: screen-inset
d_germ <- d |>
  ppl_utils$unnest_data_drivercatalog(schemas_all = dat$schemas, get_germline = TRUE)
d_germ$res |>
  reactable_wrapdown(
    descriptions = d_germ$schema$schema[c("field", "description")],
    id = paste0(tbl_nm, "_germline"),
    pagination = TRUE
  )
```

::::

### GermDels

```{r}
#| label: purple_germdeltsv
#| column: screen-inset
tbl_nm <- "purple_germdeltsv"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
d$res |>
  reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```

:::
