---
title: "TEAL"
execute: 
  echo: false
html-table-processing: none
---


```{r}
#| label: pkg_load
#| warning: false
#| message: false
{
  use("dplyr")
  use("tibble", "tibble")
  # box_path <- system.file("website/boxbox", package = "tidywigits")
  box_path <- here::here("inst/website/boxbox")
  options(box.path = box_path)
  box::use(
    wigits/utils[get_data, unnest_data, unnest_data_multi],
    wigits/table[reactable_wrapdown],
  )
}
```

```{r}
#| label: data_setup
dat <- get_data()
tool <- "teal"
dat$data <- dat$data |>
  dplyr::filter(grepl(tool, .data$tool_parser))
dat$schemas <- dat$schemas |>
  dplyr::filter(.data$tool == {{ tool }})
```

## Telomeric length and content

```{r}
#| label: teal_tellength
tbl_nm <- "teal_tellength"
d <- dat$data |>
  unnest_data_multi(tbl_nm, schemas_all = dat$schemas, subnest = "tellength")
d$res |>
  dplyr::select(-"prefix") |>
  reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```

## Telomeric rearrangements

```{r}
#| label: teal_breakend
tbl_nm <- "teal_breakend"
d <- dat$data |>
  unnest_data(tbl_nm, schemas_all = dat$schemas)
d$res |>
  reactable_wrapdown(
    descriptions = d$schema$schema[c("field", "description")],
    id = tbl_nm,
    pagination = TRUE
  )
```


::: {.callout-tip}
## TODO

- TODO1
:::
