description:
  'Counts of alignments for each FLAG type.'
raw:
  flagstats:
    description: 'Counts of alignments for each FLAG type.'
    pattern: "\\.flagstat$"
    ftype: 'txt'
    schema:
      latest:
        - field: 'dummy'
          type: 'char'
