version: "v0.0.1"
tidy:
  flagstat:
    description: 'Counts of alignments for each FLAG type.'
    schema:
      - field: 'passed_or_failed'
        type: 'char'
        description: 'QC passed or failed'
      - field: 'total'
        type: 'float'
        description: 'total number of reads that are QC pass and fail'
      - field: 'primary'
        type: 'float'
        description: 'neither secondary nor supplementary'
      - field: 'secondary'
        type: 'float'
        description: 'secondary'
      - field: 'suppl'
        type: 'float'
        description: 'supplementary'
      - field: 'dup'
        type: 'float'
        description: 'dup'
      - field: 'primary_dup'
        type: 'float'
        description: 'dup and neither secondary nor supplementary'
      - field: 'mapped'
        type: 'float'
        description: 'not unmap'
      - field: 'primary_map'
        type: 'float'
        description: 'not unmap, not secondary, and not supplementary'
      - field: 'paired_in_seq'
        type: 'float'
        description: 'paired'
      - field: 'read1'
        type: 'float'
        description: 'both paired and read1'
      - field: 'read2'
        type: 'float'
        description: 'both paired and read2'
      - field: 'proper_pair'
        type: 'float'
        description: 'both paired and proper_pair, not unmap'
      - field: 'both_map'
        type: 'float'
        description: 'paired and neither unmap nor munmap'
      - field: 'singletons'
        type: 'float'
        description: 'both paired and munmap, and not unmap'
      - field: 'matemap_diff'
        type: 'float'
        description: 'paired and neither unmap nor munmap, and mrnm not equal to rname'
      - field: 'matemap_diff_mapq5'
        type: 'float'
        description: 'paired and neither unmap nor munmap, and mrnm not equal to rname, and mapq >= 5'
      - field: 'mapped_pct'
        type: 'float'
        description: 'percentage of total reads mapped'
      - field: 'primary_map_pct'
        type: 'float'
        description: 'percentage of total primary reads'
      - field: 'proper_pair_pct'
        type: 'float'
        description: 'percentage against total pairs'
      - field: 'singletons_pct'
        type: 'float'
        description: 'percentage against total pairs'
