version: "v0.0.1"
tidy:
  bafpcf:
    description: 'BAF segments using PCF algorithm.'
    schema:
      - field: 'sampleid'
        type: 'char'
        description: 'sample ID'
      - field: 'chrom'
        type: 'char'
        description: 'chromosome'
      - field: 'arm'
        type: 'char'
        description: 'chromosome arm'
      - field: 'start_pos'
        type: 'int'
        description: 'start position'
      - field: 'end_pos'
        type: 'int'
        description: 'end position'
      - field: 'n_probes'
        type: 'int'
        description: 'number of probes'
      - field: 'mean'
        type: 'float'
        description: 'mean BAF value'
  baftsv:
    description: 'BAF for reference and tumor at each heterozygous site.'
    schema:
      - field: 'chrom'
        type: 'char'
        description: 'chromosome'
      - field: 'pos'
        type: 'int'
        description: 'position of site'
      - field: 'baf_tumor'
        type: 'float'
        description: 'tumor BAF'
      - field: 'bafmod_tumor'
        type: 'float'
        description: 'tumor BAF modified'
      - field: 'dp_tumor'
        type: 'int'
        description: 'tumor depth'
      - field: 'baf_normal'
        type: 'float'
        description: 'normal BAF'
      - field: 'bafmod_normal'
        type: 'float'
        description: 'normal BAF modified'
      - field: 'dp_normal'
        type: 'int'
        description: 'normal depth'
  contaminationtsv:
    description: 'Entry at each homozygous site in the reference and tumor.'
    schema:
      - field: 'chrom'
        type: 'char'
        description: 'chromosome'
      - field: 'pos'
        type: 'int'
        description: 'position of site'
      - field: 'ref'
        type: 'char'
        description: 'reference allele'
      - field: 'alt'
        type: 'char'
        description: 'alternate allele'
      - field: 'dp_normal'
        type: 'int'
        description: 'normal depth'
      - field: 'refsup_normal'
        type: 'int'
        description: 'normal reference support'
      - field: 'altsup_normal'
        type: 'int'
        description: 'normal alternate support'
      - field: 'dp_tumor'
        type: 'int'
        description: 'tumor depth'
      - field: 'refsup_tumor'
        type: 'int'
        description: 'tumor reference support'
      - field: 'altsup_tumor'
        type: 'int'
        description: 'tumor alternate support'
  homozygousregion:
    description: 'Regions of homozygosity found in the reference.'
    schema:
      - field: 'chrom'
        type: 'char'
        description: 'chromosome'
      - field: 'pos_start'
        type: 'int'
        description: 'start position'
      - field: 'pos_end'
        type: 'int'
        description: 'end position'
      - field: 'n_snp'
        type: 'int'
        description: 'SNP number'
      - field: 'n_hom'
        type: 'int'
        description: 'homozygous number'
      - field: 'n_het'
        type: 'int'
        description: 'heterozygous number'
      - field: 'filter'
        type: 'char'
        description: 'filter'
  qc:
    description: 'AMBER QC'
    schema:
      - field: 'qcstatus'
        type: 'char'
        description: 'QC status'
      - field: 'contamination'
        type: 'float'
        description: 'contamination percentage'
      - field: 'consanguinity'
        type: 'float'
        description: 'consanguinity proportion'
      - field: 'upd'
        type: 'char'
        description: 'uniparental disomy'
