tidy:
  gcmed:
    description: 'GC median read depth.'
    schema:
      latest:
        tbl1:
          - field: 'gc_bucket'
            type: 'char'
            description: 'GC bucket number'
          - field: 'median'
            type: 'float'
            description: 'median read depth in bucket'
  ratiomed:
    description: 'Chromosome median ratios.'
    schema:
      latest:
        tbl1:
          - field: 'chromosome'
            type: 'char'
            description: 'chromosome'
          - field: 'median_ratio'
            type: 'float'
            description: 'median ratio'
          - field: 'count'
            type: 'int'
            description: 'count'
  ratiotsv:
    description:
      'Read counts and ratios (with reference or supposed diploid regions).'
    schema:
      latest:
        tbl1:
          - field: 'chromosome'
            type: 'char'
            description: 'chromosome'
          - field: 'position'
            type: 'int'
            description: 'position'
          - field: 'dp_ref'
            type: 'float'
            description: 'reference read depth'
          - field: 'dp_tumor'
            type: 'float'
            description: 'tumor read depth'
          - field: 'gc_ratio_ref'
            type: 'float'
            description: 'reference GC ratio'
          - field: 'gc_ratio_tumor'
            type: 'float'
            description: 'tumor GC ratio'
          - field: 'gc_diploid_ratio_ref'
            type: 'float'
            description: 'reference GC diploid ratio'
          - field: 'gc_content_ref'
            type: 'float'
            description: 'reference GC content'
          - field: 'gc_content_tumor'
            type: 'float'
            description: 'tumor GC content'
  ratiopcf:
    description:
      'Segmented regions determined from the ratios (piecewise constant fit).'
    schema:
      latest:
        tbl1:
          - field: 'sample_id'
            type: 'char'
            description: 'sample ID'
          - field: 'chrom'
            type: 'char'
            description: 'chromosome'
          - field: 'arm'
            type: 'char'
            description: 'chromosome arm'
          - field: 'start_pos'
            type: 'int'
            description: 'start position'
          - field: 'end_pos'
            type: 'int'
            description: 'end position'
          - field: 'n_probes'
            type: 'int'
            description: 'number of probes'
          - field: 'mean'
            type: 'float'
            description: 'mean'
  version:
    description: 'Version of the tool'
    schema:
      latest:
        tbl1:
          - field: 'version'
            type: 'char'
            description: 'version of the tool'
          - field: 'date_build'
            type: 'char'
            description: 'build date'
