# Generated by roxytest: do not edit by hand!

# File R/Cobalt.R: @testexamples

test_that("Function Cobalt() @ L16", {
  
  cls <- Cobalt
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "cobalt_run1"
  obj <- cls$new(indir)
  obj$nemofy(diro = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "cobalt.*parquet", full.names = FALSE))
  expect_equal(length(lf), 5)
})

