# Generated by roxytest: do not edit by hand!

# File R/Alignments.R: @testexamples

test_that("Function Alignments() @ L16", {
  
  cls <- Alignments
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "alignments_run1"
  obj <- cls$new(indir)
  obj$nemofy(odir = odir, format = "parquet", id = id)
  (lf <- list.files(odir, pattern = "alignments.*parquet", full.names = FALSE))
  expect_equal(grepv("parquet", lf), "sample1_alignments_dupfreq.parquet")
})

