# Generated by roxytest: do not edit by hand!

# File R/Peach.R: @testexamples

test_that("Function Peach() @ L16", {
  
  cls <- Peach
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "peach_run1"
  obj <- cls$new(indir)
  obj$nemofy(diro = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "peach.*parquet", full.names = FALSE))
  expect_equal(length(lf), 5)
})

