# Generated by roxytest: do not edit by hand!

# File R/Sage.R: @testexamples

test_that("Function Sage() @ L16", {
  
  cls <- Sage
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "sage_run1"
  obj <- cls$new(indir)
  obj$nemofy(odir = odir, format = "parquet", id = id)
  (lf <- list.files(odir, pattern = "sage.*parquet", full.names = FALSE))
  expect_equal(length(lf), 10)
})

