# Generated by roxytest: do not edit by hand!

# File R/Sigs.R: @testexamples

test_that("Function Sigs() @ L16", {
  
  cls <- Sigs
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "sigs_run1"
  obj <- cls$new(indir)
  obj$nemofy(odir = odir, format = "parquet", id = id)
  (lf <- list.files(odir, pattern = "sigs.*parquet", full.names = FALSE))
  expect_equal(length(lf), 2)
})

