# Generated by roxytest: do not edit by hand!

# File R/Cider.R: @testexamples

test_that("Function Cider() @ L16", {
  
  cls <- Cider
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "cider_run1"
  obj <- cls$new(indir)
  obj$nemofy(diro = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "cider.*parquet", full.names = FALSE))
  expect_equal(length(lf), 3)
})

