# Generated by roxytest: do not edit by hand!

# File R/Purple.R: @testexamples

test_that("Function Purple() @ L16", {
  
  cls <- Purple
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "purple_run1"
  obj <- cls$new(indir)
  obj$nemofy(diro = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "purple.*parquet", full.names = FALSE))
  expect_equal(length(lf), 11)
})


test_that("Function purple_plot_getter() @ L202", {
  
  x <- tempdir()
  cp_dir <- file.path(tempdir(), "cpdir")
  file.create(file.path(x, paste0("sample1.", c("circos", "copynumber", "map"), ".png")))
  (d1 <- purple_plot_getter(x))
  (d2 <- purple_plot_getter(x, cp_dir))
  expect_equal(nrow(d1), 3)
  expect_equal(ncol(d1), 6)
  expect_equal(ncol(d2), 7)
})

