# Generated by roxytest: do not edit by hand!

# File R/Virusbreakend.R: @testexamples

test_that("Function Virusbreakend() @ L16", {
  
  cls <- Virusbreakend
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "virusbreakend_run1"
  obj <- cls$new(indir)
  obj$nemofy(odir = odir, format = "parquet", id = id)
  (lf <- list.files(odir, pattern = "virusbreakend.*parquet", full.names = FALSE))
  expect_equal(length(lf), 1)
})

