# Generated by roxytest: do not edit by hand!

# File R/Bamtools.R: @testexamples

test_that("Function Bamtools() @ L16", {
  
  cls <- Bamtools
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "bamtools_run1"
  obj <- cls$new(indir)
  obj$nemofy(odir = odir, format = "parquet", id = id)
  (lf <- list.files(odir, pattern = "bamtools.*parquet", full.names = FALSE))
  expect_equal(length(lf), 11)
})

