# Generated by roxytest: do not edit by hand!

# File R/Purple.R: @testexamples

test_that("Function Purple() @ L16", {
  
  cls <- Purple
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "purple_run1"
  obj <- cls$new(indir)
  obj$nemofy(odir = odir, format = "parquet", id = id)
  (lf <- list.files(odir, pattern = "purple.*parquet", full.names = FALSE))
  expect_equal(length(lf), 11)
})


test_that("Function purple_plot_getter() @ L195", {
  
  x <- tempdir()
  file.create(file.path(x, paste0("sample1.", c("circos", "copynumber", "map"), ".png")))
  (d <- purple_plot_getter(x))
  expect_equal(nrow(d), 3)
})

