# Generated by roxytest: do not edit by hand!

# File R/Neo.R: @testexamples

test_that("Function Neo() @ L16", {
  
  cls <- Neo
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "neo_run1"
  obj <- cls$new(indir)
  obj$nemofy(diro = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "neo.*parquet", full.names = FALSE))
  expect_equal(length(lf), 2)
})

