# Generated by roxytest: do not edit by hand!

# File R/write.R: @testexamples

test_that("Function valid_out_fmt() @ L87", {
  
  valid_out_fmt("tsv")
  expect_true(valid_out_fmt("tsv"))
  expect_error(valid_out_fmt("foo"))
  expect_error(valid_out_fmt(c("tsv", "csv")))
})

