# Generated by roxytest: do not edit by hand!

# File R/Linx.R: @testexamples

test_that("Function Linx() @ L16", {
  
  cls <- Linx
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "linx_run1"
  obj <- cls$new(indir)
  obj$nemofy(diro = odir, format = "parquet", input_id = id)
  (lf <- list.files(odir, pattern = "linx.*parquet", full.names = FALSE))
  expect_equal(length(lf), 20)
})

