# Generated by roxytest: do not edit by hand!

# File R/Cuppa.R: @testexamples

test_that("Function Cuppa() @ L16", {
  
  cls <- Cuppa
  indir <- system.file("extdata/oa", package = "tidywigits")
  odir <- tempdir()
  id <- "cuppa_run1"
  obj <- cls$new(indir)
  obj$nemofy(odir = odir, format = "parquet", id = id)
  (lf <- list.files(odir, pattern = "cuppa.*parquet", full.names = FALSE))
  expect_equal(length(lf), 3)
})

