# Generated by roxytest: do not edit by hand!

# File R/Config.R: @testexamples

test_that("Function Config() @ L16", {
  
  tool <- "isofox"
  conf <- Config$new(tool)
  conf$.raw_schemas_all()
  conf$.tidy_schemas_all()
  conf$.tidy_descriptions()
  
  expect_true(conf$.raw_schemas_valid())
})

