# Generated by roxytest: do not edit by hand!

# File R/utils.R: @testexamples

test_that("Function list_files_dir() @ L110", {
  
  d <- system.file("R", package = "tidywigits")
  x <- list_files_dir(d)
  expect_equal(names(x), c("bname", "size", "lastmodified", "path"))
})

