description: 'Lists CDR3 sequences for each of the IG and TCR loci, including an
  abundance estimate, incomplete rearrangements and IGK-KDE deletions.'
raw:
  blastn:
    description: 'BLASTn hits.'
    pattern: "\\.cider\\.blastn_match\\.tsv\\.gz$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'cdr3Seq'
        type: 'char'
      - field: 'cdr3AA'
        type: 'char'
      - field: 'matchType'
        type: 'char'
      - field: 'gene'
        type: 'char'
      - field: 'functionality'
        type: 'char'
      - field: 'pIdent'
        type: 'float'
      - field: 'seqLength'
        type: 'float'
      - field: 'alignStart'
        type: 'float'
      - field: 'alignEnd'
        type: 'float'
      - field: 'alignGaps'
        type: 'float'
      - field: 'alignEValue'
        type: 'float'
      - field: 'alignBitScore'
        type: 'float'
      - field: 'refStrand'
        type: 'char'
      - field: 'refStart'
        type: 'float'
      - field: 'refEnd'
        type: 'float'
      - field: 'refContig'
        type: 'char'
      - field: 'refSeq'
        type: 'char'
  locstats:
    description: 'Locus stats.'
    pattern: "\\.cider\\.locus_stats\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'locus'
        type: 'char'
      - field: 'readsUsed'
        type: 'float'
      - field: 'readsTotal'
        type: 'float'
      - field: 'downSampled'
        type: 'char'
      - field: 'sequences'
        type: 'float'
      - field: 'passSequences'
        type: 'float'
  vdj:
    description: 'VDJ sequences.'
    pattern: "\\.cider\\.vdj\\.tsv.gz$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'cdr3Seq'
        type: 'char'
      - field: 'cdr3AA'
        type: 'char'
      - field: 'locus'
        type: 'char'
      - field: 'filter'
        type: 'char'
      - field: 'blastnStatus'
        type: 'char'
      - field: 'minHighQualBaseReads'
        type: 'float'
      - field: 'assignedReads'
        type: 'float'
      - field: 'vAlignedReads'
        type: 'float'
      - field: 'jAlignedReads'
        type: 'float'
      - field: 'inFrame'
        type: 'char'
      - field: 'containsStop'
        type: 'char'
      - field: 'vType'
        type: 'char'
      - field: 'vAnchorStart'
        type: 'float'
      - field: 'vAnchorEnd'
        type: 'float'
      - field: 'vAnchorSeq'
        type: 'char'
      - field: 'vAnchorTemplateSeq'
        type: 'char'
      - field: 'vAnchorAA'
        type: 'char'
      - field: 'vAnchorTemplateAA'
        type: 'char'
      - field: 'vMatchMethod'
        type: 'char'
      - field: 'vSimilarityScore'
        type: 'float'
      - field: 'vNonSplitReads'
        type: 'float'
      - field: 'jType'
        type: 'char'
      - field: 'jAnchorStart'
        type: 'float'
      - field: 'jAnchorEnd'
        type: 'float'
      - field: 'jAnchorSeq'
        type: 'char'
      - field: 'jAnchorTemplateSeq'
        type: 'char'
      - field: 'jAnchorAA'
        type: 'char'
      - field: 'jAnchorTemplateAA'
        type: 'char'
      - field: 'jMatchMethod'
        type: 'char'
      - field: 'jSimilarityScore'
        type: 'float'
      - field: 'jNonSplitReads'
        type: 'float'
      - field: 'vGene'
        type: 'char'
      - field: 'vPIdent'
        type: 'float'
      - field: 'vAlignStart'
        type: 'float'
      - field: 'vAlignEnd'
        type: 'float'
      - field: 'dGene'
        type: 'char'
      - field: 'dPIdent'
        type: 'char'
      - field: 'dAlignStart'
        type: 'char'
      - field: 'dAlignEnd'
        type: 'char'
      - field: 'jGene'
        type: 'char'
      - field: 'jPIdent'
        type: 'float'
      - field: 'jAlignStart'
        type: 'float'
      - field: 'jAlignEnd'
        type: 'float'
      - field: 'vPrimerMatches'
        type: 'float'
      - field: 'jPrimerMatches'
        type: 'float'
      - field: 'layoutId'
        type: 'char'
      - field: 'fullSeq'
        type: 'char'
      - field: 'support'
        type: 'char'
