tidy:
  blastn:
    description: 'BLASTn hits.'
    schema:
      latest:
        tbl1:
        - field: 'cdr3_seq'
          type: 'char'
          description: 'CDR3 nucleotide sequence. If either the V or J anchor is missing only the first 63 bases of sequence are shown'
        - field: 'cdr3_aa'
          type: 'char'
          description: 'CDR3 aa sequence. If either the V or J anchor is missing only the first 63 bases of sequence are shown'
        - field: 'match_type'
          type: 'char'
          description: 'match type'
        - field: 'gene'
          type: 'char'
          description: 'gene name'
        - field: 'functionality'
          type: 'char'
          description: 'functionality'
        - field: 'p_ident'
          type: 'float'
          description: 'percentage of identical positions'
        - field: 'seq_length'
          type: 'float'
          description: 'sequence length'
        - field: 'align_start'
          type: 'float'
          description: 'start of alignment in query'
        - field: 'align_end'
          type: 'float'
          description: 'end of alignment in query'
        - field: 'align_gaps'
          type: 'float'
          description: 'number of gaps in alignment'
        - field: 'align_evalue'
          type: 'float'
          description: 'alignment e-value (lower is better)'
        - field: 'align_bitscore'
          type: 'float'
          description: 'alignment bit score (higher is better)'
        - field: 'ref_strand'
          type: 'char'
          description: 'reference strand'
        - field: 'ref_start'
          type: 'float'
          description: 'reference start'
        - field: 'ref_end'
          type: 'float'
          description: 'reference end'
        - field: 'ref_contig'
          type: 'char'
          description: 'reference contig'
        - field: 'ref_seq'
          type: 'char'
          description: 'reference sequence'
  locstats:
    description: 'Locus stats.'
    schema:
      latest:
        tbl1:
        - field: 'locus'
          type: 'char'
          description: 'Ig/TCR locus'
        - field: 'reads_used'
          type: 'float'
          description: 'number of reads used to build the VDJ sequences - differs from readsTotal by quality filtering and downsample.'
        - field: 'reads_total'
          type: 'float'
          description: 'number of reads found mapped to the locus'
        - field: 'downsampled'
          type: 'char'
          description: 'true if downsampled'
        - field: 'sequences'
          type: 'float'
          description: 'number of sequences found'
        - field: 'sequences_pass'
          type: 'float'
          description: 'number of PASS sequences found'
  vdj:
    description: 'VDJ sequences.'
    schema:
      latest:
        tbl1:
        - field: 'cdr3_seq'
          type: 'char'
          description: 'CDR3 nucleotide sequence. If either the V or J anchor is missing only the first 63 bases of sequence are shown'
        - field: 'cdr3_aa'
          type: 'char'
          description: 'CDR3 aa sequence. If either the V or J anchor is missing only the first 63 bases of sequence are shown'
        - field: 'locus'
          type: 'char'
          description: 'Ig/TCR locus of the sequence'
        - field: 'filter'
          type: 'char'
          description: 'PASS if viable CDR3 sequence or one or more filter reasons'
        - field: 'blastn_status'
          type: 'char'
          description: 'SKIPPED_BLASTN, V_D_J, V_J, V_D, D_J, V_ONLY, D_ONLY, J_ONLY, NO_REARRANGEMENT, NO_VDJ_ALIGNMENT'
        - field: 'min_high_qual_base_reads'
          type: 'float'
          description: 'number of reads in the least supported base in the CDR3 region or for the first 63 bases of the candidate CDR3 sequence if only one anchor is found'
        - field: 'assigned_reads'
          type: 'float'
          description: 'total reads assigned to candidate sequence'
        - field: 'v_aligned_reads'
          type: 'float'
          description: 'number of reads initially aligned to V gene'
        - field: 'j_aligned_reads'
          type: 'float'
          description: 'number of reads initially aligned to J gene'
        - field: 'in_frame'
          type: 'char'
          description: 'CDR3 sequence is inframe'
        - field: 'contains_stop'
          type: 'char'
          description: 'CDR3 contains stop codon'
        - field: 'v_type'
          type: 'char'
          description: '{IGKV;IGLV;IGHV;TRAV;TRBV;TRDV;TRGV}'
        - field: 'v_anchor_start'
          type: 'float'
          description: 'position of V anchor start in nt sequence'
        - field: 'v_anchor_end'
          type: 'float'
          description: 'position of V anchor end in nt sequence'
        - field: 'v_anchor_seq'
          type: 'char'
          description: 'V anchor sequence in nt'
        - field: 'v_anchor_template_seq'
          type: 'char'
          description: 'best scoring V template anchor in nt (or null if read aligned to V anchor)'
        - field: 'v_anchor_aa'
          type: 'char'
          description: 'V anchor sequence in AA'
        - field: 'v_anchor_template_aa'
          type: 'char'
          description: 'best scoring V template Anchor in AA (or null if read aligned to V anchor)'
        - field: 'v_match_method'
          type: 'char'
          description: 'V match method'
        - field: 'v_similarity_score'
          type: 'float'
          description: 'blosum similarity score for template anchor (or null if read aligned to V anchor)'
        - field: 'v_non_split_reads'
          type: 'float'
          description: 'count of reads supporting sequence with at least 30 aligned bases either side of last base of conserved C'
        - field: 'j_type'
          type: 'char'
          description: '{IGHJ;IGKJ;IGK-KDE,IGLJ;TRAJ;TRBJ;TRDJ;TRGJ}'
        - field: 'j_anchor_start'
          type: 'float'
          description: 'position of J anchor start in nt sequence'
        - field: 'j_anchor_end'
          type: 'float'
          description: 'position of J anchor end in nt sequence'
        - field: 'j_anchor_seq'
          type: 'char'
          description: 'J anchor sequence in nt'
        - field: 'j_anchor_template_seq'
          type: 'char'
          description: 'best scoring J template anchor in nt (or null if read aligned to J anchor)'
        - field: 'j_anchor_aa'
          type: 'char'
          description: 'J anchor sequence in AA'
        - field: 'j_anchor_template_aa'
          type: 'char'
          description: 'best scoring J template Anchor in AA (or null if read aligned to J anchor)'
        - field: 'j_match_method'
          type: 'char'
          description: 'J match method'
        - field: 'j_similarity_score'
          type: 'float'
          description: 'Blosum62 similarity score for template anchor (or null if read aligned to J anchor)'
        - field: 'j_non_split_reads'
          type: 'float'
          description: 'count of reads supporting sequence with at least 30 aligned bases either side of first base of conserved W/F'
        - field: 'v_gene'
          type: 'char'
          description: 'the V gene allele that this sequence is aligned to'
        - field: 'v_pident'
          type: 'float'
          description: 'the align sequence % identity with the V gene'
        - field: 'v_align_start'
          type: 'float'
          description: 'start of the alignment with the V gene'
        - field: 'v_align_end'
          type: 'float'
          description: 'end of the alignment with the V gene'
        - field: 'd_gene'
          type: 'char'
          description: 'the D gene allele that this sequence is aligned to'
        - field: 'd_pident'
          type: 'float'
          description: 'the align sequence % identity with the D gene'
        - field: 'd_align_start'
          type: 'float'
          description: 'start of the alignment with the D gene'
        - field: 'd_align_end'
          type: 'float'
          description: 'end of the alignment with the D gene'
        - field: 'j_gene'
          type: 'char'
          description: 'the J gene allele that this sequence is aligned to'
        - field: 'j_pident'
          type: 'float'
          description: 'the align sequence % identity with the J gene'
        - field: 'j_align_start'
          type: 'float'
          description: 'start of the alignment with the J gene'
        - field: 'j_align_end'
          type: 'float'
          description: 'end of the alignment with the J gene'
        - field: 'v_primer_matches'
          type: 'float'
          description: 'V primer matches'
        - field: 'j_primer_matches'
          type: 'float'
          description: 'J primer matches'
        - field: 'layout_id'
          type: 'char'
          description: 'layout ID'
        - field: 'full_seq'
          type: 'char'
          description: 'full consensus sequence in nucleotides'
        - field: 'support'
          type: 'char'
          description: 'counts of high quality base support at each nucleotide (radix-36 ASCII encoded)'
