description:
  'Alignment duplicate read metrics.'
raw:
  dupfreq:
    description: 'Duplicate read count and frequency.'
    pattern: "\\.duplicate_freq\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'DuplicateReadCount'
          type: 'char'
        - field: 'Frequency'
          type: 'float'
  markdup:
    description: 'Picard duplication metrics.'
    pattern: "\\.md\\.metrics$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'LIBRARY'
          type: 'char'
        - field: 'UNPAIRED_READS_EXAMINED'
          type: 'float'
        - field: 'READ_PAIRS_EXAMINED'
          type: 'float'
        - field: 'SECONDARY_OR_SUPPLEMENTARY_RDS'
          type: 'float'
        - field: 'UNMAPPED_READS'
          type: 'float'
        - field: 'UNPAIRED_READ_DUPLICATES'
          type: 'float'
        - field: 'READ_PAIR_DUPLICATES'
          type: 'float'
        - field: 'READ_PAIR_OPTICAL_DUPLICATES'
          type: 'float'
        - field: 'PERCENT_DUPLICATION'
          type: 'float'
        - field: 'ESTIMATED_LIBRARY_SIZE'
          type: 'float'
        - field: 'SPLIT_HERE'
          type: 'char'
        - field: 'BIN'
          type: 'float'
        - field: 'CoverageMult'
          type: 'float'
        - field: 'all_sets'
          type: 'float'
        - field: 'optical_sets'
          type: 'float'
        - field: 'non_optical_sets'
          type: 'float'
