description:
  'Just a single file with DuplicateReadCount and Frequency'
raw:
  dupfreq:
    description: 'Duplicate read count and frequency'
    pattern: "\\.duplicate_freq\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'DuplicateReadCount'
          type: 'char'
        - field: 'Frequency'
          type: 'int'
