tidy:
  dupfreq:
    description: 'Duplicate read count and frequency.'
    schema:
      latest:
        tbl1:
          - field: 'duplicate_read_count'
            type: 'char'
            description: 'Duplicate read count'
          - field: 'frequency'
            type: 'float'
            description: 'Frequency of duplicate reads'
