tidy:
  dupfreq:
    description: 'Duplicate read count and frequency.'
    schema:
      latest:
        - field: 'duplicate_read_count'
          type: 'char'
          description: 'Duplicate read count'
        - field: 'frequency'
          type: 'int'
          description: 'Frequency of duplicate reads'
