tidy:
  dupfreq:
    description: 'Duplicate read count and frequency.'
    schema:
      latest:
        tbl1:
          - field: 'duplicate_read_count'
            type: 'char'
            description: 'Duplicate read count'
          - field: 'frequency'
            type: 'float'
            description: 'Frequency of duplicate reads'
  markdup:
    description: 'Picard duplication metrics.'
    schema:
      latest:
        tbl1:
          - field: 'library'
            type: 'char'
            description: 'library on which the duplicate marking was performed'
          - field: 'unpaired_reads_examined'
            type: 'float'
            description: 'number of mapped reads examined which did not have a mapped mate pair'
          - field: 'read_pairs_examined'
            type: 'float'
            description: 'number of mapped read pairs examined'
          - field: 'secondary_or_supplementary_reads'
            type: 'float'
            description: 'number of reads that were either secondary or supplementary'
          - field: 'unmapped_reads'
            type: 'float'
            description: 'total number of unmapped reads examined'
          - field: 'unpaired_read_duplicates'
            type: 'float'
            description: 'number of fragments that were marked as duplicates'
          - field: 'read_pair_duplicates'
            type: 'float'
            description: 'number of read pairs that were marked as duplicates'
          - field: 'read_pair_optical_duplicates'
            type: 'float'
            description: 'number of read pair duplicates that were caused by optical duplication'
          - field: 'percent_duplication'
            type: 'float'
            description: 'fraction of mapped sequence that is marked as duplicate'
          - field: 'estimated_library_size'
            type: 'float'
            description: 'estimated number of unique molecules in the library based on PE duplication'
          - field: 'SPLIT_HERE'
            type: 'char'
            description: 'internal use for splitting the schema.'
          - field: 'bin'
            type: 'float'
            description: 'coverage bin (maybe?)'
          - field: 'cov_mult'
            type: 'float'
            description: 'coverage multiple'
          - field: 'all_sets'
            type: 'float'
            description: 'all sets'
          - field: 'optical_sets'
            type: 'float'
            description: 'optical sets'
          - field: 'non_optical_sets'
            type: 'float'
            description: 'non optical sets'
