description: 'Post-process final VIRUSBreakend summary.'
raw:
  annotated:
    description: 'Processed oncoviral call/annotation data.'
    comment: 'The column "blacklisted" was added in v1.5.'
    pattern: "\\.virus\\.annotated\\.tsv$"
    ftype: 'tsv'
    schema:
      v1.3:
        - field: 'taxid'
          type: 'char'
        - field: 'name'
          type: 'char'
        - field: 'qcStatus'
          type: 'char'
        - field: 'integrations'
          type: 'float'
        - field: 'interpretation'
          type: 'char'
        - field: 'percentageCovered'
          type: 'float'
        - field: 'meanCoverage'
          type: 'float'
        - field: 'expectedClonalCoverage'
          type: 'float'
        - field: 'reported'
          type: 'char'
        - field: 'driverLikelihood'
          type: 'char'
      latest:
        - field: 'taxid'
          type: 'char'
        - field: 'name'
          type: 'char'
        - field: 'qcStatus'
          type: 'char'
        - field: 'integrations'
          type: 'float'
        - field: 'interpretation'
          type: 'char'
        - field: 'percentageCovered'
          type: 'float'
        - field: 'meanCoverage'
          type: 'float'
        - field: 'expectedClonalCoverage'
          type: 'float'
        - field: 'reported'
          type: 'char'
        - field: 'blacklisted'
          type: 'char'
        - field: 'driverLikelihood'
          type: 'char'
