description: 'Structural variant caller optimised for short read sequencing.'
raw:
  prepfraglen:
    description: 'Fragment length stats.'
    pattern: "\\.esvee\\.prep\\.fragment_length\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'FragmentLength'
        type: 'float'
      - field: 'Count'
        type: 'float'
  prepdiscstats:
    description: 'Discordant read stats.'
    pattern: "\\.esvee\\.prep\\.disc_stats\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'TotalReads'
        type: 'float'
      - field: 'WrittenReads'
        type: 'float'
      - field: 'Translocation'
        type: 'float'
      - field: 'ShortInv'
        type: 'float'
      - field: 'DelDup10K'
        type: 'float'
      - field: 'DelDup100K'
        type: 'float'
      - field: 'DelDupLong'
        type: 'float'
      - field: 'Inv100K'
        type: 'float'
      - field: 'InvLong'
        type: 'float'
  prepjunction:
    description: 'Candidate junctions.'
    pattern: "\\.esvee\\.prep\\.junction\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'Chromosome'
        type: 'char'
      - field: 'Position'
        type: 'float'
      - field: 'Orientation'
        type: 'float'
      - field: 'JunctionFrags'
        type: 'float'
      - field: 'ExactSupportFrags'
        type: 'float'
      - field: 'OtherSupportFrags'
        type: 'float'
      - field: 'LowMapQualFrags'
        type: 'float'
      - field: 'MaxQual'
        type: 'float'
      - field: 'ExtraInfo'
        type: 'float'
      - field: 'Indel'
        type: 'char'
      - field: 'Hotspot'
        type: 'char'
      - field: 'InitialReadId'
        type: 'char'
  assemblephased:
    description: 'Phased assemblies.'
    pattern: "\\.esvee\\.phased_assembly\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'AssemblyIds'
        type: 'char'
      - field: 'AssemblyInfo'
        type: 'char'
      - field: 'Merged'
        type: 'char'
      - field: 'SequenceLength'
        type: 'float'
      - field: 'AssemblyCigar'
        type: 'char'
      - field: 'FullSequence'
        type: 'char'
  assembleassembly:
    description: 'Breakend assemblies.'
    pattern: "\\.esvee\\.assembly\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'Id'
        type: 'char'
      - field: 'Chromosome'
        type: 'char'
      - field: 'JuncPosition'
        type: 'float'
      - field: 'JuncOrientation'
        type: 'float'
      - field: 'JuncType'
        type: 'char'
      - field: 'ExtBaseLength'
        type: 'float'
      - field: 'RefBasePosition'
        type: 'float'
      - field: 'RefBaseLength'
        type: 'float'
      - field: 'RefBaseCigar'
        type: 'char'
      - field: 'SplitFrags'
        type: 'float'
      - field: 'RefSplitFrags'
        type: 'float'
      - field: 'DiscFrags'
        type: 'float'
      - field: 'RefDiscFrags'
        type: 'float'
      - field: 'Outcome'
        type: 'char'
      - field: 'PhaseGroupId'
        type: 'float'
      - field: 'PhaseGroupCount'
        type: 'float'
      - field: 'PhaseSetId'
        type: 'char'
      - field: 'PhaseSetCount'
        type: 'float'
      - field: 'SplitLinks'
        type: 'char'
      - field: 'FacingLinks'
        type: 'char'
      - field: 'SvType'
        type: 'char'
      - field: 'SvLength'
        type: 'float'
      - field: 'InsertedBases'
        type: 'char'
      - field: 'OverlapBases'
        type: 'char'
      - field: 'RefLinkedFrags'
        type: 'char'
      - field: 'SecondaryLinks'
        type: 'char'
      - field: 'MismatchReads'
        type: 'float'
      - field: 'RefBaseTrimmed'
        type: 'char'
      - field: 'RefBaseTrimLength'
        type: 'float'
      - field: 'JunctionSequence'
        type: 'char'
      - field: 'RefBaseSequence'
        type: 'char'
      - field: 'IsLINE'
        type: 'char'
      - field: 'RefBaseCandidates'
        type: 'float'
      - field: 'UnmappedCandidates'
        type: 'float'
      - field: 'JuncSupps'
        type: 'float'
      - field: 'JuncIndels'
        type: 'float'
      - field: 'JuncMateConcord'
        type: 'float'
      - field: 'JuncMateRefSide'
        type: 'float'
      - field: 'JuncMateDiscordRemote'
        type: 'float'
      - field: 'JuncMateDiscordRefSide'
        type: 'float'
      - field: 'JuncMateUnmappedRemote'
        type: 'float'
      - field: 'JuncMateUnmappedRefSide'
        type: 'float'
      - field: 'RemoteRegionCount'
        type: 'float'
      - field: 'RemoteRegionInfo'
        type: 'char'
      - field: 'RemoteRegionJuncMate'
        type: 'float'
      - field: 'RemoteRegionJuncSupps'
        type: 'float'
      - field: 'RemoteRegionDiscordant'
        type: 'float'
      - field: 'AssemblyInfo'
        type: 'char'
      - field: 'InitialReadId'
        type: 'char'
      - field: 'RepeatInfo'
        type: 'char'
      - field: 'RefSideSoftClips'
        type: 'char'
      - field: 'MergedAssemblies'
        type: 'float'
      - field: 'SoftClipMatches'
        type: 'float'
      - field: 'SoftClipMismatches'
        type: 'float'
      - field: 'SoftClip2ndMaxLength'
        type: 'float'
      - field: 'RefBaseMismatches'
        type: 'float'
      - field: 'BaseTrimCount'
        type: 'float'
      - field: 'AvgNmCount'
        type: 'float'
      - field: 'AvgIndelLength'
        type: 'float'
      - field: 'AvgBaseQual'
        type: 'float'
      - field: 'AvgMapQual'
        type: 'float'
      - field: 'ExtBaseBuildInfo'
        type: 'char'
  assemblebreakend:
    description: 'Breakends.'
    pattern: "\\.esvee\\.breakend\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'Id'
        type: 'char'
      - field: 'PhaseGroupId'
        type: 'char'
      - field: 'PhaseSetId'
        type: 'char'
      - field: 'AssemblyId'
        type: 'char'
      - field: 'MateId'
        type: 'char'
      - field: 'AssemblyInfo'
        type: 'char'
      - field: 'Type'
        type: 'char'
      - field: 'Chromosome'
        type: 'char'
      - field: 'Position'
        type: 'float'
      - field: 'Orientation'
        type: 'float'
      - field: 'MateChr'
        type: 'char'
      - field: 'MatePos'
        type: 'float'
      - field: 'MateOrient'
        type: 'float'
      - field: 'Length'
        type: 'float'
      - field: 'InsertedBases'
        type: 'char'
      - field: 'Homology'
        type: 'char'
      - field: 'ConfidenceInterval'
        type: 'char'
      - field: 'InexactOffset'
        type: 'char'
      - field: 'Qual'
        type: 'float'
      - field: 'SplitFragments'
        type: 'float'
      - field: 'RefSplitFragments'
        type: 'float'
      - field: 'DiscFragments'
        type: 'float'
      - field: 'RefDiscFragments'
        type: 'float'
      - field: 'ForwardReads'
        type: 'float'
      - field: 'ReverseReads'
        type: 'float'
      - field: 'SequenceLength'
        type: 'float'
      - field: 'SegmentCount'
        type: 'float'
      - field: 'SegmentIndex'
        type: 'float'
      - field: 'SequenceIndex'
        type: 'float'
      - field: 'AlignedBases'
        type: 'float'
      - field: 'MapQual'
        type: 'float'
      - field: 'Score'
        type: 'float'
      - field: 'AdjAlignedBases'
        type: 'float'
      - field: 'AvgFragmentLength'
        type: 'float'
      - field: 'IncompleteFragments'
        type: 'float'
      - field: 'BreakendQual'
        type: 'float'
      - field: 'FacingBreakendIds'
        type: 'char'
      - field: 'AltAlignments'
        type: 'char'
  assemblealignment:
    description: 'Realigned assemblies.'
    pattern: "\\.esvee\\.alignment\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
      - field: 'AssemblyIds'
        type: 'char'
      - field: 'AssemblyInfo'
        type: 'char'
      - field: 'RefInfo'
        type: 'char'
      - field: 'RawSeqCoords'
        type: 'char'
      - field: 'AdjSeqCoords'
        type: 'char'
      - field: 'MapQual'
        type: 'float'
      - field: 'Cigar'
        type: 'char'
      - field: 'Orientation'
        type: 'float'
      - field: 'AlignedBases'
        type: 'float'
      - field: 'Score'
        type: 'float'
      - field: 'Flags'
        type: 'float'
      - field: 'NMatches'
        type: 'float'
      - field: 'XaTag'
        type: 'char'
      - field: 'MdTag'
        type: 'char'
      - field: 'CalcAlignLength'
        type: 'float'
      - field: 'ModMapQual'
        type: 'float'
      - field: 'DroppedOnRequery'
        type: 'char'
      - field: 'LinkedAltAlignment'
        type: 'char'
