tidy:
  prepfraglen:
    description: 'Fragment length stats.'
    schema:
      latest:
        tbl1:
          - field: 'fragment_length'
            type: 'float'
          - field: 'count'
            type: 'float'
  prepdiscstats:
    description: 'Discordant read stats.'
    schema:
      latest:
        tbl1:
          - field: 'tot_reads'
            type: 'float'
          - field: 'written_reads'
            type: 'float'
          - field: 'translocation'
            type: 'float'
          - field: 'short_inv'
            type: 'float'
          - field: 'del_dup_10k'
            type: 'float'
          - field: 'del_dup_100k'
            type: 'float'
          - field: 'del_dup_long'
            type: 'float'
          - field: 'inv_100k'
            type: 'float'
          - field: 'inv_long'
            type: 'float'
  prepjunction:
    description: 'Candidate junctions.'
    schema:
      latest:
        tbl1:
          - field: 'chromosome'
            type: 'char'
          - field: 'position'
            type: 'float'
          - field: 'orientation'
            type: 'float'
          - field: 'junc_frags'
            type: 'float'
          - field: 'exact_support_frags'
            type: 'float'
          - field: 'other_support_frags'
            type: 'float'
          - field: 'low_map_qual_frags'
            type: 'float'
          - field: 'max_qual'
            type: 'float'
          - field: 'extra_info'
            type: 'float'
          - field: 'indel'
            type: 'char'
          - field: 'hotspot'
            type: 'char'
          - field: 'initial_read_id'
            type: 'char'
  assemblephased:
    description: 'Phased assemblies.'
    schema:
      latest:
        tbl1:
          - field: 'assembly_ids'
            type: 'char'
          - field: 'assembly_info'
            type: 'char'
          - field: 'merged'
            type: 'char'
          - field: 'sequence_length'
            type: 'float'
          - field: 'assembly_cigar'
            type: 'char'
          - field: 'full_sequence'
            type: 'char'
  assembleassembly:
    description: 'Breakend assemblies.'
    schema:
      latest:
        tbl1:
          - field: 'id'
            type: 'char'
          - field: 'chromosome'
            type: 'char'
          - field: 'junc_position'
            type: 'float'
          - field: 'junc_orientation'
            type: 'float'
          - field: 'junc_type'
            type: 'char'
          - field: 'ext_base_length'
            type: 'float'
          - field: 'ref_base_position'
            type: 'float'
          - field: 'ref_base_length'
            type: 'float'
          - field: 'ref_base_cigar'
            type: 'char'
          - field: 'split_frags'
            type: 'float'
          - field: 'ref_split_frags'
            type: 'float'
          - field: 'disc_frags'
            type: 'float'
          - field: 'ref_disc_frags'
            type: 'float'
          - field: 'outcome'
            type: 'char'
          - field: 'phase_group_id'
            type: 'float'
          - field: 'phase_group_count'
            type: 'float'
          - field: 'phase_set_id'
            type: 'char'
          - field: 'phase_set_count'
            type: 'float'
          - field: 'split_links'
            type: 'char'
          - field: 'facing_links'
            type: 'char'
          - field: 'sv_type'
            type: 'char'
          - field: 'sv_length'
            type: 'float'
          - field: 'inserted_bases'
            type: 'char'
          - field: 'overlap_bases'
            type: 'char'
          - field: 'ref_linked_frags'
            type: 'char'
          - field: 'secondary_links'
            type: 'char'
          - field: 'mismatch_reads'
            type: 'float'
          - field: 'ref_base_trimmed'
            type: 'char'
          - field: 'ref_base_trim_length'
            type: 'float'
          - field: 'junc_sequence'
            type: 'char'
          - field: 'ref_base_sequence'
            type: 'char'
          - field: 'is_line'
            type: 'char'
          - field: 'ref_base_candidates'
            type: 'float'
          - field: 'unmapped_candidates'
            type: 'float'
          - field: 'junc_supps'
            type: 'float'
          - field: 'junc_indels'
            type: 'float'
          - field: 'junc_mate_concord'
            type: 'float'
          - field: 'junc_mate_ref_side'
            type: 'float'
          - field: 'junc_mate_discord_remote'
            type: 'float'
          - field: 'junc_mate_discord_ref_side'
            type: 'float'
          - field: 'junc_mate_unmapped_remote'
            type: 'float'
          - field: 'junc_mate_unmapped_ref_side'
            type: 'float'
          - field: 'remote_region_count'
            type: 'float'
          - field: 'remote_region_info'
            type: 'char'
          - field: 'remote_region_junc_mate'
            type: 'float'
          - field: 'remote_region_junc_supps'
            type: 'float'
          - field: 'remote_region_discordant'
            type: 'float'
          - field: 'assembly_info'
            type: 'char'
          - field: 'initial_read_id'
            type: 'char'
          - field: 'repeat_info'
            type: 'char'
          - field: 'ref_side_soft_clips'
            type: 'char'
          - field: 'merged_assemblies'
            type: 'float'
          - field: 'soft_clip_matches'
            type: 'float'
          - field: 'soft_clip_mismatches'
            type: 'float'
          - field: 'soft_clip_2nd_max_length'
            type: 'float'
          - field: 'ref_base_mismatches'
            type: 'float'
          - field: 'base_trim_count'
            type: 'float'
          - field: 'avg_nm_count'
            type: 'float'
          - field: 'avg_indel_length'
            type: 'float'
          - field: 'avg_base_qual'
            type: 'float'
          - field: 'avg_map_qual'
            type: 'float'
          - field: 'ext_base_build_info'
            type: 'char'
  assemblebreakend:
    description: 'Breakends.'
    schema:
      latest:
        tbl1:
          - field: 'id'
            type: 'char'
          - field: 'phase_group_id'
            type: 'char'
          - field: 'phase_set_id'
            type: 'char'
          - field: 'assembly_id'
            type: 'char'
          - field: 'mate_id'
            type: 'char'
          - field: 'assembly_info'
            type: 'char'
          - field: 'type'
            type: 'char'
          - field: 'chromosome'
            type: 'char'
          - field: 'position'
            type: 'float'
          - field: 'orientation'
            type: 'float'
          - field: 'mate_chr'
            type: 'char'
          - field: 'mate_pos'
            type: 'float'
          - field: 'mate_orient'
            type: 'float'
          - field: 'length'
            type: 'float'
          - field: 'inserted_bases'
            type: 'char'
          - field: 'homology'
            type: 'char'
          - field: 'confidence_interval'
            type: 'char'
          - field: 'inexact_offset'
            type: 'char'
          - field: 'qual'
            type: 'float'
          - field: 'split_fragments'
            type: 'float'
          - field: 'ref_split_fragments'
            type: 'float'
          - field: 'disc_fragments'
            type: 'float'
          - field: 'ref_disc_fragments'
            type: 'float'
          - field: 'forward_reads'
            type: 'float'
          - field: 'reverse_reads'
            type: 'float'
          - field: 'sequence_length'
            type: 'float'
          - field: 'segment_count'
            type: 'float'
          - field: 'segment_index'
            type: 'float'
          - field: 'sequence_index'
            type: 'float'
          - field: 'aligned_bases'
            type: 'float'
          - field: 'map_qual'
            type: 'float'
          - field: 'score'
            type: 'float'
          - field: 'adj_aligned_bases'
            type: 'float'
          - field: 'avg_fragment_length'
            type: 'float'
          - field: 'incomplete_fragments'
            type: 'float'
          - field: 'breakend_qual'
            type: 'float'
          - field: 'facing_breakend_ids'
            type: 'char'
          - field: 'alt_alignments'
            type: 'char'
  assemblealignment:
    description: 'Realigned assemblies.'
    schema:
      latest:
        tbl1:
          - field: 'assembly_ids'
            type: 'char'
          - field: 'assembly_info'
            type: 'char'
          - field: 'ref_info'
            type: 'char'
          - field: 'raw_seq_coords'
            type: 'char'
          - field: 'adj_seq_coords'
            type: 'char'
          - field: 'map_qual'
            type: 'float'
          - field: 'cigar'
            type: 'char'
          - field: 'orientation'
            type: 'float'
          - field: 'aligned_bases'
            type: 'float'
          - field: 'score'
            type: 'float'
          - field: 'flags'
            type: 'float'
          - field: 'n_matches'
            type: 'float'
          - field: 'xa_tag'
            type: 'char'
          - field: 'md_tag'
            type: 'char'
          - field: 'calc_align_length'
            type: 'float'
          - field: 'mod_map_qual'
            type: 'float'
          - field: 'dropped_on_requery'
            type: 'char'
          - field: 'linked_alt_alignment'
            type: 'char'
