description:
  'Counts fragment support for identifying and counting gene and transcript features using genome aligned RNASeq data.'
raw:
  summary:
    description: 'QC summary.'
    pattern: "\\.isf\\.summary\\.csv$"
    ftype: 'csv'
    schema:
      latest:
        - field: 'SampleId'
          type: 'char'
        - field: 'QcStatus'
          type: 'char'
        - field: 'TotalFragments'
          type: 'float'
        - field: 'DuplicateFragments'
          type: 'float'
        - field: 'SplicedFragmentPerc'
          type: 'float'
        - field: 'UnsplicedFragmentPerc'
          type: 'float'
        - field: 'AltFragmentPerc'
          type: 'float'
        - field: 'ChimericFragmentPerc'
          type: 'float'
        - field: 'SplicedGeneCount'
          type: 'float'
        - field: 'ReadLength'
          type: 'float'
        - field: 'FragLength5th'
          type: 'float'
        - field: 'FragLength50th'
          type: 'float'
        - field: 'FragLength95th'
          type: 'float'
        - field: 'EnrichedGenePercent'
          type: 'float'
        - field: 'MedianGCRatio'
          type: 'float'
        - field: 'ForwardStrandPercent'
          type: 'float'
  genedata:
    description: 'Gene level data.'
    pattern: "\\.isf\\.gene_data\\.csv$"
    ftype: 'csv'
    schema:
      latest:
        - field: 'GeneId'
          type: 'char'
        - field: 'GeneName'
          type: 'char'
        - field: 'Chromosome'
          type: 'char'
        - field: 'GeneLength'
          type: 'int'
        - field: 'IntronicLength'
          type: 'int'
        - field: 'TranscriptCount'
          type: 'int'
        - field: 'GeneSetId'
          type: 'char'
        - field: 'SplicedFragments'
          type: 'int'
        - field: 'UnsplicedFragments'
          type: 'int'
        - field: 'AdjTPM'
          type: 'float'
        - field: 'RawTPM'
          type: 'float'
        - field: 'FitResiduals'
          type: 'float'
        - field: 'LowMapQualFrags'
          type: 'float'
  transdata:
    description: 'Transcript level data.'
    pattern: "\\.isf\\.transcript_data\\.csv$"
    ftype: 'csv'
    schema:
      - field: 'GeneId'
        type: 'char'
      - field: 'GeneName'
        type: 'char'
      - field: 'TransId'
        type: 'char'
      - field: 'TransName'
        type: 'char'
      - field: 'ExonCount'
        type: 'int'
      - field: 'TranscriptLength'
        type: 'int'
      - field: 'EffectiveLength'
        type: 'int'
      - field: 'FittedFragments'
        type: 'float'
      - field: 'RawFittedFragments'
        type: 'float'
      - field: 'AdjTPM'
        type: 'float'
      - field: 'RawTPM'
        type: 'float'
      - field: 'TranscriptBasesCovered'
        type: 'float'
      - field: 'SJSupported'
        type: 'float'
      - field: 'UniqueSJSupported'
        type: 'float'
      - field: 'UniqueSJFragments'
        type: 'float'
      - field: 'UniqueNonSJFragments'
        type: 'float'
      - field: 'DiscordantFragments'
        type: 'float'
      - field: 'LowMapQualFrags'
        type: 'float'
  altsj:
    description: 'Alternate splice junctions.'
    pattern: "\\.isf\\.alt_splice_junc\\.csv$"
    ftype: 'csv'
    schema:
      latest:
        - field: 'GeneId'
          type: 'char'
        - field: 'GeneName'
          type: 'char'
        - field: 'Chromosome'
          type: 'char'
        - field: 'SjStart'
          type: 'float'
        - field: 'SjEnd'
          type: 'float'
        - field: 'Type'
          type: 'char'
        - field: 'FragCount'
          type: 'float'
        - field: 'DepthStart'
          type: 'float'
        - field: 'DepthEnd'
          type: 'float'
        - field: 'RegionStart'
          type: 'char'
        - field: 'RegionEnd'
          type: 'char'
        - field: 'BasesStart'
          type: 'char'
        - field: 'BasesEnd'
          type: 'char'
        - field: 'TransStart'
          type: 'char'
        - field: 'TransEnd'
          type: 'char'
        - field: 'NearestStartExon'
          type: 'float'
        - field: 'NearestEndExon'
          type: 'float'
        - field: 'InitialReadId'
          type: 'char'
  retintron:
    description: 'Retained introns.'
    pattern: "\\.isf\\.retained_intron\\.csv$"
    ftype: 'csv'
    schema:
      latest:
        - field: 'GeneId'
          type: 'char'
        - field: 'GeneName'
          type: 'char'
        - field: 'Chromosome'
          type: 'char'
        - field: 'Strand'
          type: 'float'
        - field: 'Position'
          type: 'float'
        - field: 'Type'
          type: 'char'
        - field: 'FragCount'
          type: 'float'
        - field: 'SplicedFragCount'
          type: 'float'
        - field: 'TotalDepth'
          type: 'float'
        - field: 'TranscriptInfo'
          type: 'char'
  fusionsall:
    description: 'All fusions.'
    pattern: "\\.isf\\.fusions\\.csv$"
    ftype: 'csv'
    schema:
      latest:
        - field: 'FusionId'
          type: 'char'
        - field: 'Valid'
          type: 'char'
        - field: 'ChrUp'
          type: 'char'
        - field: 'PosUp'
          type: 'float'
        - field: 'OrientUp'
          type: 'float'
        - field: 'GeneIdUp'
          type: 'char'
        - field: 'GeneNameUp'
          type: 'char'
        - field: 'StrandUp'
          type: 'float'
        - field: 'JuncTypeUp'
          type: 'char'
        - field: 'CoverageUp'
          type: 'float'
        - field: 'MaxAnchorLengthUp'
          type: 'float'
        - field: 'TransDataUp'
          type: 'char'
        - field: 'ChrDown'
          type: 'char'
        - field: 'PosDown'
          type: 'float'
        - field: 'OrientDown'
          type: 'float'
        - field: 'GeneIdDown'
          type: 'char'
        - field: 'GeneNameDown'
          type: 'char'
        - field: 'StrandDown'
          type: 'float'
        - field: 'JuncTypeDown'
          type: 'char'
        - field: 'CoverageDown'
          type: 'float'
        - field: 'MaxAnchorLengthDown'
          type: 'float'
        - field: 'TransDataDown'
          type: 'char'
        - field: 'SVType'
          type: 'char'
        - field: 'TotalFragments'
          type: 'float'
        - field: 'SplitFrags'
          type: 'float'
        - field: 'RealignedFrags'
          type: 'float'
        - field: 'DiscordantFrags'
          type: 'float'
        - field: 'RelatedSplicedIds'
          type: 'char'
        - field: 'CohortCount'
          type: 'float'
        - field: 'ReadType'
          type: 'char'
        - field: 'InitReadId'
          type: 'char'
  fusionspass:
    description: 'Passed fusions.'
    pattern: "\\.isf\\.pass_fusions\\.csv$"
    ftype: 'csv'
    schema:
      latest:
        - field: 'FusionId'
          type: 'char'
        - field: 'Valid'
          type: 'char'
        - field: 'ChrUp'
          type: 'char'
        - field: 'PosUp'
          type: 'float'
        - field: 'OrientUp'
          type: 'float'
        - field: 'GeneIdUp'
          type: 'char'
        - field: 'GeneNameUp'
          type: 'char'
        - field: 'StrandUp'
          type: 'float'
        - field: 'JuncTypeUp'
          type: 'char'
        - field: 'CoverageUp'
          type: 'float'
        - field: 'MaxAnchorLengthUp'
          type: 'float'
        - field: 'ChrDown'
          type: 'char'
        - field: 'PosDown'
          type: 'float'
        - field: 'OrientDown'
          type: 'float'
        - field: 'GeneIdDown'
          type: 'char'
        - field: 'GeneNameDown'
          type: 'char'
        - field: 'StrandDown'
          type: 'float'
        - field: 'JuncTypeDown'
          type: 'char'
        - field: 'CoverageDown'
          type: 'float'
        - field: 'MaxAnchorLengthDown'
          type: 'float'
        - field: 'SVType'
          type: 'char'
        - field: 'TotalFragments'
          type: 'float'
        - field: 'SplitFrags'
          type: 'float'
        - field: 'RealignedFrags'
          type: 'float'
        - field: 'DiscordantFrags'
          type: 'float'
        - field: 'RelatedSplicedIds'
          type: 'char'
        - field: 'CohortCount'
          type: 'float'
        - field: 'Filter'
          type: 'char'
        - field: 'KnownFusionType'
          type: 'char'
  genecollection:
    description: 'Gene collection.'
    pattern: "\\.isf\\.gene_collection\\.csv$"
    ftype: 'csv'
    schema:
      latest:
        - field: 'GeneSetId'
          type: 'char'
        - field: 'GeneCount'
          type: 'float'
        - field: 'Chromosome'
          type: 'char'
        - field: 'RangeStart'
          type: 'float'
        - field: 'RangeEnd'
          type: 'float'
        - field: 'TotalFragments'
          type: 'float'
        - field: 'Duplicates'
          type: 'float'
        - field: 'SupportingTrans'
          type: 'float'
        - field: 'Unspliced'
          type: 'float'
        - field: 'AltSJ'
          type: 'float'
        - field: 'Chimeric'
          type: 'float'
        - field: 'LowMapQual'
          type: 'float'
        - field: 'ForwardStrand'
          type: 'float'
        - field: 'ReverseStrand'
          type: 'float'
        - field: 'Genes'
          type: 'char'
