description: 'Classifier of HOmologous Recombination Deficiency.'
raw:
  prediction:
    description: 'Predictions from the CHORD random forest.'
    pattern: "_chord_prediction\\.txt$|\\.chord\\.prediction\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'sample'
          type: 'char'
        - field: 'p_BRCA1'
          type: 'float'
        - field: 'p_BRCA2'
          type: 'float'
        - field: 'p_hrd'
          type: 'float'
        - field: 'hr_status'
          type: 'char'
        - field: 'hrd_type'
          type: 'char'
        - field: 'remarks_hr_status'
          type: 'char'
        - field: 'remarks_hrd_type'
          type: 'char'
  signatures:
    description: 'Counts of SNV, INDEL and SV contexts.'
    pattern: "_chord_signatures\\.txt$|\\.chord\\.mutation_contexts\\.tsv$"
    ftype: 'tsv'
    schema:
      latest:
        - field: 'sample_id'
          type: 'char'
        - field: 'A[C>A]A'
          type: 'int'
        - field: 'A[C>A]C'
          type: 'int'
        - field: 'A[C>A]G'
          type: 'int'
        - field: 'A[C>A]T'
          type: 'int'
        - field: 'C[C>A]A'
          type: 'int'
        - field: 'C[C>A]C'
          type: 'int'
        - field: 'C[C>A]G'
          type: 'int'
        - field: 'C[C>A]T'
          type: 'int'
        - field: 'G[C>A]A'
          type: 'int'
        - field: 'G[C>A]C'
          type: 'int'
        - field: 'G[C>A]G'
          type: 'int'
        - field: 'G[C>A]T'
          type: 'int'
        - field: 'T[C>A]A'
          type: 'int'
        - field: 'T[C>A]C'
          type: 'int'
        - field: 'T[C>A]G'
          type: 'int'
        - field: 'T[C>A]T'
          type: 'int'
        - field: 'A[C>G]A'
          type: 'int'
        - field: 'A[C>G]C'
          type: 'int'
        - field: 'A[C>G]G'
          type: 'int'
        - field: 'A[C>G]T'
          type: 'int'
        - field: 'C[C>G]A'
          type: 'int'
        - field: 'C[C>G]C'
          type: 'int'
        - field: 'C[C>G]G'
          type: 'int'
        - field: 'C[C>G]T'
          type: 'int'
        - field: 'G[C>G]A'
          type: 'int'
        - field: 'G[C>G]C'
          type: 'int'
        - field: 'G[C>G]G'
          type: 'int'
        - field: 'G[C>G]T'
          type: 'int'
        - field: 'T[C>G]A'
          type: 'int'
        - field: 'T[C>G]C'
          type: 'int'
        - field: 'T[C>G]G'
          type: 'int'
        - field: 'T[C>G]T'
          type: 'int'
        - field: 'A[C>T]A'
          type: 'int'
        - field: 'A[C>T]C'
          type: 'int'
        - field: 'A[C>T]G'
          type: 'int'
        - field: 'A[C>T]T'
          type: 'int'
        - field: 'C[C>T]A'
          type: 'int'
        - field: 'C[C>T]C'
          type: 'int'
        - field: 'C[C>T]G'
          type: 'int'
        - field: 'C[C>T]T'
          type: 'int'
        - field: 'G[C>T]A'
          type: 'int'
        - field: 'G[C>T]C'
          type: 'int'
        - field: 'G[C>T]G'
          type: 'int'
        - field: 'G[C>T]T'
          type: 'int'
        - field: 'T[C>T]A'
          type: 'int'
        - field: 'T[C>T]C'
          type: 'int'
        - field: 'T[C>T]G'
          type: 'int'
        - field: 'T[C>T]T'
          type: 'int'
        - field: 'A[T>A]A'
          type: 'int'
        - field: 'A[T>A]C'
          type: 'int'
        - field: 'A[T>A]G'
          type: 'int'
        - field: 'A[T>A]T'
          type: 'int'
        - field: 'C[T>A]A'
          type: 'int'
        - field: 'C[T>A]C'
          type: 'int'
        - field: 'C[T>A]G'
          type: 'int'
        - field: 'C[T>A]T'
          type: 'int'
        - field: 'G[T>A]A'
          type: 'int'
        - field: 'G[T>A]C'
          type: 'int'
        - field: 'G[T>A]G'
          type: 'int'
        - field: 'G[T>A]T'
          type: 'int'
        - field: 'T[T>A]A'
          type: 'int'
        - field: 'T[T>A]C'
          type: 'int'
        - field: 'T[T>A]G'
          type: 'int'
        - field: 'T[T>A]T'
          type: 'int'
        - field: 'A[T>C]A'
          type: 'int'
        - field: 'A[T>C]C'
          type: 'int'
        - field: 'A[T>C]G'
          type: 'int'
        - field: 'A[T>C]T'
          type: 'int'
        - field: 'C[T>C]A'
          type: 'int'
        - field: 'C[T>C]C'
          type: 'int'
        - field: 'C[T>C]G'
          type: 'int'
        - field: 'C[T>C]T'
          type: 'int'
        - field: 'G[T>C]A'
          type: 'int'
        - field: 'G[T>C]C'
          type: 'int'
        - field: 'G[T>C]G'
          type: 'int'
        - field: 'G[T>C]T'
          type: 'int'
        - field: 'T[T>C]A'
          type: 'int'
        - field: 'T[T>C]C'
          type: 'int'
        - field: 'T[T>C]G'
          type: 'int'
        - field: 'T[T>C]T'
          type: 'int'
        - field: 'A[T>G]A'
          type: 'int'
        - field: 'A[T>G]C'
          type: 'int'
        - field: 'A[T>G]G'
          type: 'int'
        - field: 'A[T>G]T'
          type: 'int'
        - field: 'C[T>G]A'
          type: 'int'
        - field: 'C[T>G]C'
          type: 'int'
        - field: 'C[T>G]G'
          type: 'int'
        - field: 'C[T>G]T'
          type: 'int'
        - field: 'G[T>G]A'
          type: 'int'
        - field: 'G[T>G]C'
          type: 'int'
        - field: 'G[T>G]G'
          type: 'int'
        - field: 'G[T>G]T'
          type: 'int'
        - field: 'T[T>G]A'
          type: 'int'
        - field: 'T[T>G]C'
          type: 'int'
        - field: 'T[T>G]G'
          type: 'int'
        - field: 'T[T>G]T'
          type: 'int'
        - field: 'del.rep.len.1'
          type: 'int'
        - field: 'del.rep.len.2'
          type: 'int'
        - field: 'del.rep.len.3'
          type: 'int'
        - field: 'del.rep.len.4'
          type: 'int'
        - field: 'del.rep.len.5'
          type: 'int'
        - field: 'ins.rep.len.1'
          type: 'int'
        - field: 'ins.rep.len.2'
          type: 'int'
        - field: 'ins.rep.len.3'
          type: 'int'
        - field: 'ins.rep.len.4'
          type: 'int'
        - field: 'ins.rep.len.5'
          type: 'int'
        - field: 'del.mh.bimh.1'
          type: 'int'
        - field: 'del.mh.bimh.2'
          type: 'int'
        - field: 'del.mh.bimh.3'
          type: 'int'
        - field: 'del.mh.bimh.4'
          type: 'int'
        - field: 'del.mh.bimh.5'
          type: 'int'
        - field: 'ins.mh.bimh.1'
          type: 'int'
        - field: 'ins.mh.bimh.2'
          type: 'int'
        - field: 'ins.mh.bimh.3'
          type: 'int'
        - field: 'ins.mh.bimh.4'
          type: 'int'
        - field: 'ins.mh.bimh.5'
          type: 'int'
        - field: 'del.none.len.1'
          type: 'int'
        - field: 'del.none.len.2'
          type: 'int'
        - field: 'del.none.len.3'
          type: 'int'
        - field: 'del.none.len.4'
          type: 'int'
        - field: 'del.none.len.5'
          type: 'int'
        - field: 'ins.none.len.1'
          type: 'int'
        - field: 'ins.none.len.2'
          type: 'int'
        - field: 'ins.none.len.3'
          type: 'int'
        - field: 'ins.none.len.4'
          type: 'int'
        - field: 'ins.none.len.5'
          type: 'int'
        - field: 'DEL_0e00_1e03_bp'
          type: 'int'
        - field: 'DEL_1e03_1e04_bp'
          type: 'int'
        - field: 'DEL_1e04_1e05_bp'
          type: 'int'
        - field: 'DEL_1e05_1e06_bp'
          type: 'int'
        - field: 'DEL_1e06_1e07_bp'
          type: 'int'
        - field: 'DEL_1e07_Inf_bp'
          type: 'int'
        - field: 'DUP_0e00_1e03_bp'
          type: 'int'
        - field: 'DUP_1e03_1e04_bp'
          type: 'int'
        - field: 'DUP_1e04_1e05_bp'
          type: 'int'
        - field: 'DUP_1e05_1e06_bp'
          type: 'int'
        - field: 'DUP_1e06_1e07_bp'
          type: 'int'
        - field: 'DUP_1e07_Inf_bp'
          type: 'int'
        - field: 'INV_0e00_1e03_bp'
          type: 'int'
        - field: 'INV_1e03_1e04_bp'
          type: 'int'
        - field: 'INV_1e04_1e05_bp'
          type: 'int'
        - field: 'INV_1e05_1e06_bp'
          type: 'int'
        - field: 'INV_1e06_1e07_bp'
          type: 'int'
        - field: 'INV_1e07_Inf_bp'
          type: 'int'
        - field: 'TRA'
          type: 'int'
