version: 'v0.0.1'
tidy:
  prediction:
    description: 'Predictions from the CHORD random forest.'
    schema:
      - field: 'p_brca1'
        type: 'float'
        description: 'probability of BRCA1-type HRD'
      - field: 'p_brca2'
        type: 'float'
        description: 'probability of BRCA2-type HRD'
      - field: 'p_hrd'
        type: 'float'
        description: 'probability of HRD'
      - field: 'hr_status'
        type: 'char'
        description: 'HR status (deficient or proficient)'
      - field: 'hrd_type'
        type: 'char'
        description: 'HRD type (BRCA1 or BRCA2)'
      - field: 'remarks_hr_status'
        type: 'char'
        description: 'remarks on HR status'
      - field: 'remarks_hrd_type'
        type: 'char'
        description: 'remarks on HRD type'
  signatures:
    description: 'Counts of SNV, INDEL and SV contexts.'
    schema:
      - field: 'signature'
        type: 'char'
        description: 'signature context'
      - field: 'count'
        type: 'int'
        description: 'count of signature'
