version: 'v0.0.1'
tidy:
  prediction:
    description: 'Predictions from the CHORD random forest.'
    schema:
      - field: 'sample'
        type: 'char'
        description: 'sample ID'
      - field: 'p_brca1'
        type: 'float'
        description: 'probability of BRCA1-type HRD'
      - field: 'p_brca2'
        type: 'float'
        description: 'probability of BRCA2-type HRD'
      - field: 'p_hrd'
        type: 'float'
        description: 'probability of HRD'
      - field: 'hr_status'
        type: 'char'
        description: 'HR status (deficient or proficient)'
      - field: 'hrd_type'
        type: 'char'
        description: 'HRD type (BRCA1 or BRCA2)'
      - field: 'remarks_hr_status'
        type: 'char'
        description: 'remarks on HR status'
      - field: 'remarks_hrd_type'
        type: 'char'
        description: 'remarks on HRD type'
  signatures:
    description: 'Counts of SNV, INDEL and SV contexts.'
    schema:
      - field: 'sample'
        type: 'char'
        description: 'Sample identifier'
      - field: 'a_c_a_a'
        type: 'int'
        description: 'Count of A[C>A]A'
      - field: 'a_c_a_c'
        type: 'int'
        description: 'Count of A[C>A]C'
      - field: 'a_c_a_g'
        type: 'int'
        description: 'Count of A[C>A]G'
      - field: 'a_c_a_t'
        type: 'int'
        description: 'Count of A[C>A]T'
      - field: 'c_c_a_a'
        type: 'int'
        description: 'Count of C[C>A]A'
      - field: 'c_c_a_c'
        type: 'int'
        description: 'Count of C[C>A]C'
      - field: 'c_c_a_g'
        type: 'int'
        description: 'Count of C[C>A]G'
      - field: 'c_c_a_t'
        type: 'int'
        description: 'Count of C[C>A]T'
      - field: 'g_c_a_a'
        type: 'int'
        description: 'Count of G[C>A]A'
      - field: 'g_c_a_c'
        type: 'int'
        description: 'Count of G[C>A]C'
      - field: 'g_c_a_g'
        type: 'int'
        description: 'Count of G[C>A]G'
      - field: 'g_c_a_t'
        type: 'int'
        description: 'Count of G[C>A]T'
      - field: 't_c_a_a'
        type: 'int'
        description: 'Count of T[C>A]A'
      - field: 't_c_a_c'
        type: 'int'
        description: 'Count of T[C>A]C'
      - field: 't_c_a_g'
        type: 'int'
        description: 'Count of T[C>A]G'
      - field: 't_c_a_t'
        type: 'int'
        description: 'Count of T[C>A]T'
      - field: 'a_c_g_a'
        type: 'int'
        description: 'Count of A[C>G]A'
      - field: 'a_c_g_c'
        type: 'int'
        description: 'Count of A[C>G]C'
      - field: 'a_c_g_g'
        type: 'int'
        description: 'Count of A[C>G]G'
      - field: 'a_c_g_t'
        type: 'int'
        description: 'Count of A[C>G]T'
      - field: 'c_c_g_a'
        type: 'int'
        description: 'Count of C[C>G]A'
      - field: 'c_c_g_c'
        type: 'int'
        description: 'Count of C[C>G]C'
      - field: 'c_c_g_g'
        type: 'int'
        description: 'Count of C[C>G]G'
      - field: 'c_c_g_t'
        type: 'int'
        description: 'Count of C[C>G]T'
      - field: 'g_c_g_a'
        type: 'int'
        description: 'Count of G[C>G]A'
      - field: 'g_c_g_c'
        type: 'int'
        description: 'Count of G[C>G]C'
      - field: 'g_c_g_g'
        type: 'int'
        description: 'Count of G[C>G]G'
      - field: 'g_c_g_t'
        type: 'int'
        description: 'Count of G[C>G]T'
      - field: 't_c_g_a'
        type: 'int'
        description: 'Count of T[C>G]A'
      - field: 't_c_g_c'
        type: 'int'
        description: 'Count of T[C>G]C'
      - field: 't_c_g_g'
        type: 'int'
        description: 'Count of T[C>G]G'
      - field: 't_c_g_t'
        type: 'int'
        description: 'Count of T[C>G]T'
      - field: 'a_c_t_a'
        type: 'int'
        description: 'Count of A[C>T]A'
      - field: 'a_c_t_c'
        type: 'int'
        description: 'Count of A[C>T]C'
      - field: 'a_c_t_g'
        type: 'int'
        description: 'Count of A[C>T]G'
      - field: 'a_c_t_t'
        type: 'int'
        description: 'Count of A[C>T]T'
      - field: 'c_c_t_a'
        type: 'int'
        description: 'Count of C[C>T]A'
      - field: 'c_c_t_c'
        type: 'int'
        description: 'Count of C[C>T]C'
      - field: 'c_c_t_g'
        type: 'int'
        description: 'Count of C[C>T]G'
      - field: 'c_c_t_t'
        type: 'int'
        description: 'Count of C[C>T]T'
      - field: 'g_c_t_a'
        type: 'int'
        description: 'Count of G[C>T]A'
      - field: 'g_c_t_c'
        type: 'int'
        description: 'Count of G[C>T]C'
      - field: 'g_c_t_g'
        type: 'int'
        description: 'Count of G[C>T]G'
      - field: 'g_c_t_t'
        type: 'int'
        description: 'Count of G[C>T]T'
      - field: 't_c_t_a'
        type: 'int'
        description: 'Count of T[C>T]A'
      - field: 't_c_t_c'
        type: 'int'
        description: 'Count of T[C>T]C'
      - field: 't_c_t_g'
        type: 'int'
        description: 'Count of T[C>T]G'
      - field: 't_c_t_t'
        type: 'int'
        description: 'Count of T[C>T]T'
      - field: 'a_t_a_a'
        type: 'int'
        description: 'Count of A[T>A]A'
      - field: 'a_t_a_c'
        type: 'int'
        description: 'Count of A[T>A]C'
      - field: 'a_t_a_g'
        type: 'int'
        description: 'Count of A[T>A]G'
      - field: 'a_t_a_t'
        type: 'int'
        description: 'Count of A[T>A]T'
      - field: 'c_t_a_a'
        type: 'int'
        description: 'Count of C[T>A]A'
      - field: 'c_t_a_c'
        type: 'int'
        description: 'Count of C[T>A]C'
      - field: 'c_t_a_g'
        type: 'int'
        description: 'Count of C[T>A]G'
      - field: 'c_t_a_t'
        type: 'int'
        description: 'Count of C[T>A]T'
      - field: 'g_t_a_a'
        type: 'int'
        description: 'Count of G[T>A]A'
      - field: 'g_t_a_c'
        type: 'int'
        description: 'Count of G[T>A]C'
      - field: 'g_t_a_g'
        type: 'int'
        description: 'Count of G[T>A]G'
      - field: 'g_t_a_t'
        type: 'int'
        description: 'Count of G[T>A]T'
      - field: 't_t_a_a'
        type: 'int'
        description: 'Count of T[T>A]A'
      - field: 't_t_a_c'
        type: 'int'
        description: 'Count of T[T>A]C'
      - field: 't_t_a_g'
        type: 'int'
        description: 'Count of T[T>A]G'
      - field: 't_t_a_t'
        type: 'int'
        description: 'Count of T[T>A]T'
      - field: 'a_t_c_a'
        type: 'int'
        description: 'Count of A[T>C]A'
      - field: 'a_t_c_c'
        type: 'int'
        description: 'Count of A[T>C]C'
      - field: 'a_t_c_g'
        type: 'int'
        description: 'Count of A[T>C]G'
      - field: 'a_t_c_t'
        type: 'int'
        description: 'Count of A[T>C]T'
      - field: 'c_t_c_a'
        type: 'int'
        description: 'Count of C[T>C]A'
      - field: 'c_t_c_c'
        type: 'int'
        description: 'Count of C[T>C]C'
      - field: 'c_t_c_g'
        type: 'int'
        description: 'Count of C[T>C]G'
      - field: 'c_t_c_t'
        type: 'int'
        description: 'Count of C[T>C]T'
      - field: 'g_t_c_a'
        type: 'int'
        description: 'Count of G[T>C]A'
      - field: 'g_t_c_c'
        type: 'int'
        description: 'Count of G[T>C]C'
      - field: 'g_t_c_g'
        type: 'int'
        description: 'Count of G[T>C]G'
      - field: 'g_t_c_t'
        type: 'int'
        description: 'Count of G[T>C]T'
      - field: 't_t_c_a'
        type: 'int'
        description: 'Count of T[T>C]A'
      - field: 't_t_c_c'
        type: 'int'
        description: 'Count of T[T>C]C'
      - field: 't_t_c_g'
        type: 'int'
        description: 'Count of T[T>C]G'
      - field: 't_t_c_t'
        type: 'int'
        description: 'Count of T[T>C]T'
      - field: 'a_t_g_a'
        type: 'int'
        description: 'Count of A[T>G]A'
      - field: 'a_t_g_c'
        type: 'int'
        description: 'Count of A[T>G]C'
      - field: 'a_t_g_g'
        type: 'int'
        description: 'Count of A[T>G]G'
      - field: 'a_t_g_t'
        type: 'int'
        description: 'Count of A[T>G]T'
      - field: 'c_t_g_a'
        type: 'int'
        description: 'Count of C[T>G]A'
      - field: 'c_t_g_c'
        type: 'int'
        description: 'Count of C[T>G]C'
      - field: 'c_t_g_g'
        type: 'int'
        description: 'Count of C[T>G]G'
      - field: 'c_t_g_t'
        type: 'int'
        description: 'Count of C[T>G]T'
      - field: 'g_t_g_a'
        type: 'int'
        description: 'Count of G[T>G]A'
      - field: 'g_t_g_c'
        type: 'int'
        description: 'Count of G[T>G]C'
      - field: 'g_t_g_g'
        type: 'int'
        description: 'Count of G[T>G]G'
      - field: 'g_t_g_t'
        type: 'int'
        description: 'Count of G[T>G]T'
      - field: 't_t_g_a'
        type: 'int'
        description: 'Count of T[T>G]A'
      - field: 't_t_g_c'
        type: 'int'
        description: 'Count of T[T>G]C'
      - field: 't_t_g_g'
        type: 'int'
        description: 'Count of T[T>G]G'
      - field: 't_t_g_t'
        type: 'int'
        description: 'Count of T[T>G]T'
      - field: 'del_rep_len_1'
        type: 'int'
        description: 'Count of del.rep.len.1'
      - field: 'del_rep_len_2'
        type: 'int'
        description: 'Count of del.rep.len.2'
      - field: 'del_rep_len_3'
        type: 'int'
        description: 'Count of del.rep.len.3'
      - field: 'del_rep_len_4'
        type: 'int'
        description: 'Count of del.rep.len.4'
      - field: 'del_rep_len_5'
        type: 'int'
        description: 'Count of del.rep.len.5'
      - field: 'ins_rep_len_1'
        type: 'int'
        description: 'Count of ins.rep.len.1'
      - field: 'ins_rep_len_2'
        type: 'int'
        description: 'Count of ins.rep.len.2'
      - field: 'ins_rep_len_3'
        type: 'int'
        description: 'Count of ins.rep.len.3'
      - field: 'ins_rep_len_4'
        type: 'int'
        description: 'Count of ins.rep.len.4'
      - field: 'ins_rep_len_5'
        type: 'int'
        description: 'Count of ins.rep.len.5'
      - field: 'del_mh_bimh_1'
        type: 'int'
        description: 'Count of del.mh.bimh.1'
      - field: 'del_mh_bimh_2'
        type: 'int'
        description: 'Count of del.mh.bimh.2'
      - field: 'del_mh_bimh_3'
        type: 'int'
        description: 'Count of del.mh.bimh.3'
      - field: 'del_mh_bimh_4'
        type: 'int'
        description: 'Count of del.mh.bimh.4'
      - field: 'del_mh_bimh_5'
        type: 'int'
        description: 'Count of del.mh.bimh.5'
      - field: 'ins_mh_bimh_1'
        type: 'int'
        description: 'Count of ins.mh.bimh.1'
      - field: 'ins_mh_bimh_2'
        type: 'int'
        description: 'Count of ins.mh.bimh.2'
      - field: 'ins_mh_bimh_3'
        type: 'int'
        description: 'Count of ins.mh.bimh.3'
      - field: 'ins_mh_bimh_4'
        type: 'int'
        description: 'Count of ins.mh.bimh.4'
      - field: 'ins_mh_bimh_5'
        type: 'int'
        description: 'Count of ins.mh.bimh.5'
      - field: 'del_none_len_1'
        type: 'int'
        description: 'Count of del.none.len.1'
      - field: 'del_none_len_2'
        type: 'int'
        description: 'Count of del.none.len.2'
      - field: 'del_none_len_3'
        type: 'int'
        description: 'Count of del.none.len.3'
      - field: 'del_none_len_4'
        type: 'int'
        description: 'Count of del.none.len.4'
      - field: 'del_none_len_5'
        type: 'int'
        description: 'Count of del.none.len.5'
      - field: 'ins_none_len_1'
        type: 'int'
        description: 'Count of ins.none.len.1'
      - field: 'ins_none_len_2'
        type: 'int'
        description: 'Count of ins.none.len.2'
      - field: 'ins_none_len_3'
        type: 'int'
        description: 'Count of ins.none.len.3'
      - field: 'ins_none_len_4'
        type: 'int'
        description: 'Count of ins.none.len.4'
      - field: 'ins_none_len_5'
        type: 'int'
        description: 'Count of ins.none.len.5'
      - field: 'del_0e00_1e03_bp'
        type: 'int'
        description: 'Count of DEL_0e00_1e03_bp'
      - field: 'del_1e03_1e04_bp'
        type: 'int'
        description: 'Count of DEL_1e03_1e04_bp'
      - field: 'del_1e04_1e05_bp'
        type: 'int'
        description: 'Count of DEL_1e04_1e05_bp'
      - field: 'del_1e05_1e06_bp'
        type: 'int'
        description: 'Count of DEL_1e05_1e06_bp'
      - field: 'del_1e06_1e07_bp'
        type: 'int'
        description: 'Count of DEL_1e06_1e07_bp'
      - field: 'del_1e07_inf_bp'
        type: 'int'
        description: 'Count of DEL_1e07_Inf_bp'
      - field: 'dup_0e00_1e03_bp'
        type: 'int'
        description: 'Count of DUP_0e00_1e03_bp'
      - field: 'dup_1e03_1e04_bp'
        type: 'int'
        description: 'Count of DUP_1e03_1e04_bp'
      - field: 'dup_1e04_1e05_bp'
        type: 'int'
        description: 'Count of DUP_1e04_1e05_bp'
      - field: 'dup_1e05_1e06_bp'
        type: 'int'
        description: 'Count of DUP_1e05_1e06_bp'
      - field: 'dup_1e06_1e07_bp'
        type: 'int'
        description: 'Count of DUP_1e06_1e07_bp'
      - field: 'dup_1e07_inf_bp'
        type: 'int'
        description: 'Count of DUP_1e07_Inf_bp'
      - field: 'inv_0e00_1e03_bp'
        type: 'int'
        description: 'Count of INV_0e00_1e03_bp'
      - field: 'inv_1e03_1e04_bp'
        type: 'int'
        description: 'Count of INV_1e03_1e04_bp'
      - field: 'inv_1e04_1e05_bp'
        type: 'int'
        description: 'Count of INV_1e04_1e05_bp'
      - field: 'inv_1e05_1e06_bp'
        type: 'int'
        description: 'Count of INV_1e05_1e06_bp'
      - field: 'inv_1e06_1e07_bp'
        type: 'int'
        description: 'Count of INV_1e06_1e07_bp'
      - field: 'inv_1e07_inf_bp'
        type: 'int'
        description: 'Count of INV_1e07_Inf_bp'
      - field: 'tra'
        type: 'int'
        description: 'Count of TRA'
