tidy:
  version:
    description: 'Version of the tool.'
    schema:
      latest:
        - field: 'version'
          type: 'char'
          description: 'version of the tool'
        - field: 'date_build'
          type: 'char'
          description: 'build date'
  cnvgenetsv:
    description: 'Copy number alterations of each gene in the HMF gene panel.'
    schema:
      latest:
        - field: 'chromosome'
          type: 'char'
          description: 'chromosome of gene'
        - field: 'start'
          type: 'float'
          description: 'start location of gene transcript'
        - field: 'end'
          type: 'float'
          description: 'end location of gene transcript'
        - field: 'gene'
          type: 'char'
          description: 'name of gene as per Ensembl and HGNC'
        - field: 'min_cn'
          type: 'float'
          description: 'minimum cn found in the gene exons'
        - field: 'max_cn'
          type: 'float'
          description: 'maximum cn found in the gene exons'
        - field: 'somatic_regions'
          type: 'float'
          description: 'count of somatic cn regions this gene spans'
        - field: 'transcript_id'
          type: 'char'
          description: 'ensembl transcript ID'
        - field: 'is_canonical'
          type: 'char'
          description: 'is canonical'
        - field: 'chromosome_band'
          type: 'char'
          description: 'chromosome band of the gene'
        - field: 'min_regions'
          type: 'float'
          description:
            'number of somatic regions inside the gene that share the min cn'
        - field: 'min_region_start'
          type: 'float'
          description:
            'start base of the cn region overlapping the gene with the minimum
            cn'
        - field: 'min_region_end'
          type: 'float'
          description:
            'end base of the cn region overlapping the gene with the minimum cn'
        - field: 'min_region_start_support'
          type: 'char'
          description:
            'start support of the cn region overlapping the gene with the
            minimum cn'
        - field: 'min_region_end_support'
          type: 'char'
          description:
            'end support of the cn region overlapping the gene with the minimum
            cn'
        - field: 'min_region_method'
          type: 'char'
          description:
            'method used to determine cn of the cn region overlapping the gene
            with the minimum cn'
        - field: 'min_minor_allele_cn'
          type: 'float'
          description:
            'minimum allele cn found over the gene exons - useful for
            identifying LOH events'
        - field: 'depth_window_count'
          type: 'float'
          description: 'count of cobalt windows covered by this segment'
  cnvsomtsv:
    description:
      'Copy number profile of all (contiguous) segments of the tumor sample.'
    schema:
      latest:
        - field: 'chromosome'
          type: 'char'
          description: 'chromosome of cn segment'
        - field: 'start'
          type: 'float'
          description: 'start base of cn segment'
        - field: 'end'
          type: 'float'
          description: 'end base of cn segment'
        - field: 'cn'
          type: 'float'
          description:
            'fitted absolute cn of segment adjusted for purity and ploidy'
        - field: 'baf_count'
          type: 'float'
          description: 'count of amber baf points covered by this segment'
        - field: 'observed_baf'
          type: 'float'
          description:
            'combined reference and tumor BAF in tumor sample unadjusted for
            purity and ploidy'
        - field: 'baf'
          type: 'float'
          description: 'tumor BAF after adjusted for purity and ploidy'
        - field: 'segment_start_support'
          type: 'char'
          description:
            'type of structural variant support for the cn breakpoint at start
            of region'
        - field: 'segment_end_support'
          type: 'char'
          description:
            'type of structural variant support for the cn breakpoint at end of
            region'
        - field: 'method'
          type: 'char'
          description: 'method used to determine the cn of the region'
        - field: 'depth_window_count'
          type: 'float'
          description: 'count of cobalt windows covered by this segment'
        - field: 'gc_content'
          type: 'float'
          description: 'proportion of segment that is G or C'
        - field: 'min_start'
          type: 'float'
          description:
            'minimum start location of this segment if there is any uncertainty'
        - field: 'max_start'
          type: 'float'
          description:
            'maximum start location of this segment if there is any uncertainty'
        - field: 'minor_allele_cn'
          type: 'float'
          description: 'cn of minor allele adjusted for purity'
        - field: 'major_allele_cn'
          type: 'float'
          description: 'cn of major allele adjusted for purity'
  drivercatalog:
    description:
      'Significant amplifications and deletions that occur in the HMF gene
      panel.'
    schema:
      latest:
        - field: 'chromosome'
          type: 'char'
          description: 'chromosome of the gene'
        - field: 'chromosome_band'
          type: 'char'
          description: 'chromosome band of driver'
        - field: 'gene'
          type: 'char'
          description: 'name of gene'
        - field: 'transcript'
          type: 'char'
          description: 'ensembl transcript ID'
        - field: 'is_canonical'
          type: 'char'
          description: 'is canonical (True/False)'
        - field: 'driver'
          type: 'char'
          description: 'driver type (amp, del, mutation)'
        - field: 'category'
          type: 'char'
          description: 'gene driver type (oncogene or tumor suppressor)'
        - field: 'likelihood_method'
          type: 'char'
          description: 'method used to determine likelihood'
        - field: 'driver_likelihood'
          type: 'float'
          description: 'likelihood that gene is a driver'
        - field: 'missense'
          type: 'float'
          description: 'number of missense variants in gene'
        - field: 'nonsense'
          type: 'float'
          description: 'number of nonsense variants in gene'
        - field: 'splice'
          type: 'float'
          description: 'number of splice variants in gene'
        - field: 'inframe'
          type: 'float'
          description: 'number of inframe variants in gene'
        - field: 'frameshift'
          type: 'float'
          description: 'number of frameshift variants in gene'
        - field: 'biallelic'
          type: 'char'
          description: 'true if any variants in the gene are biallelic'
        - field: 'min_cn'
          type: 'float'
          description: 'minimum cn found in the gene exons'
        - field: 'max_cn'
          type: 'float'
          description: 'maximum cn found in the gene exons'
  germdeltsv:
    description: 'Germline deletions.'
    schema:
      latest:
        - field: 'gene'
          type: 'char'
          description: 'name of gene as per Ensembl and HGNC'
        - field: 'chromosome'
          type: 'char'
          description: 'chromosome of gene'
        - field: 'chromosome_band'
          type: 'char'
          description: 'chromosome band of gene'
        - field: 'region_start'
          type: 'float'
          description: 'start base of deletion'
        - field: 'region_end'
          type: 'float'
          description: 'end base of deletion'
        - field: 'depth_window_count'
          type: 'float'
          description: 'count of cobalt windows covered by this segment'
        - field: 'exon_start'
          type: 'float'
          description: 'start base of deletion'
        - field: 'exon_end'
          type: 'float'
          description: 'end base of deletion'
        - field: 'detection_method'
          type: 'char'
          description: 'method used to determine the cn of the region'
        - field: 'germline_status'
          type: 'char'
          description: 'germline status of the deletion'
        - field: 'tumor_status'
          type: 'char'
          description: 'tumor status of the deletion'
        - field: 'germline_cn'
          type: 'float'
          description: 'germline cn of the deletion'
        - field: 'tumor_cn'
          type: 'float'
          description: 'tumor cn of the deletion'
        - field: 'filter'
          type: 'char'
          description: 'filter applied to the deletion'
        - field: 'cohort_frequency'
          type: 'float'
          description: 'frequency of deletion in the HMF cohort'
        - field: 'reported'
          type: 'char'
          description: 'reported deletion'
  purityrange:
    description: 'Best fit per purity sorted by score.'
    schema:
      latest:
        - field: 'purity'
          type: 'float'
          description: 'purity of tumor in the sample'
        - field: 'norm_factor'
          type: 'float'
          description: 'internal factor to convert tumor ratio to cn.'
        - field: 'score'
          type: 'float'
          description: 'score of fit (lower is better)'
        - field: 'diploid_proportion'
          type: 'float'
          description:
            'proportion of cn regions that have 1 (+- 0.2) minor and major
            allele'
        - field: 'ploidy'
          type: 'float'
          description:
            'average ploidy of the tumor sample after adjusting for purity'
        - field: 'somatic_penalty'
          type: 'float'
          description:
            'penalty from somatic variants with implied variant cn that are
            inconsistent with the minor and major allele cn'
  puritytsv:
    description: 'Purity/ploidy fit summary.'
    schema:
      latest:
        - field: 'purity'
          type: 'float'
          description: 'purity of tumor in the sample'
        - field: 'norm_factor'
          type: 'float'
          description: 'internal factor to convert tumor ratio to cn.'
        - field: 'score'
          type: 'float'
          description: 'score of fit (lower is better)'
        - field: 'diploid_proportion'
          type: 'float'
          description:
            'proportion of cn regions that have 1 (+- 0.2) minor and major
            allele'
        - field: 'ploidy'
          type: 'float'
          description:
            'average ploidy of the tumor sample after adjusting for purity'
        - field: 'gender'
          type: 'char'
          description: 'one of male or female'
        - field: 'status'
          type: 'char'
          description: 'either pass or one or more warning or fail status'
        - field: 'polyclonal_proportion'
          type: 'float'
          description:
            'proportion of copy number regions that are more than 0.25 from a
            whole cn'
        - field: 'min_purity'
          type: 'float'
          description: 'minimum purity with score within 10% of best'
        - field: 'max_purity'
          type: 'float'
          description: 'maximum purity with score within 10% of best'
        - field: 'min_ploidy'
          type: 'float'
          description: 'minimum ploidy with score within 10% of best'
        - field: 'max_ploidy'
          type: 'float'
          description: 'maximum ploidy with score within 10% of best'
        - field: 'min_diploid_proportion'
          type: 'float'
          description: 'min estimation for diploid proportion'
        - field: 'max_diploid_proportion'
          type: 'float'
          description: 'max estimation for diploid proportion'
        - field: 'somatic_penalty'
          type: 'float'
          description:
            'penalty from somatic variants with implied variant cn that are
            inconsistent with the minor and major allele cn'
        - field: 'whole_genome_duplication'
          type: 'char'
          description:
            'true if more than 10 autosomes have major allele cn > 1.5'
        - field: 'ms_indels_per_mb'
          type: 'float'
          description: 'microsatellite indels per mega base'
        - field: 'ms_status'
          type: 'char'
          description:
            'microsatellite status (msi, mss or unknown if somatic variants not
            supplied)'
        - field: 'tml'
          type: 'float'
          description:
            'tumor mutational load (# of missense variants in sample)'
        - field: 'tml_status'
          type: 'char'
          description:
            'tumor mutational load status (high, low or unknown if somatic
            variants not supplied)'
        - field: 'tmb_per_mb'
          type: 'float'
          description:
            'tumor mutational burden (#passing variants per Mb) per mega base'
        - field: 'tmb_status'
          type: 'char'
          description:
            'tumor mutational burden status (high, low or unknown if somatic
            variants not supplied)'
        - field: 'sv_tumor_mutational_burden'
          type: 'float'
          description:
            'total number of non inferred, non single passing structural
            variants detected in sample'
        - field: 'run_mode'
          type: 'char'
          description:
            'tumor_germline, tumor or germline, set based on whether a tumor
            and/or reference sample were supplied'
        - field: 'targeted'
          type: 'char'
          description: 'true if purple was run with target-region files'
  qc:
    description: 'PURPLE QC.'
    schema:
      latest:
        - field: 'qc_status'
          type: 'char'
          description: 'QC status'
        - field: 'method'
          type: 'char'
          description:
            'method used to determine the cn of the region (NORMAL,
            HIGHLY_DIPLOID, SOMATIC or NO_TUMOR)'
        - field: 'cn_segments'
          type: 'int'
          description: 'total number of cn segments in sample'
        - field: 'unsupported_cn_segments'
          type: 'int'
          description:
            'count of cn segments with no SV support on either side. A high
            number is an indicator of poor sample quality'
        - field: 'purity'
          type: 'float'
          description: 'purity of tumor in the sample'
        - field: 'gender_amber'
          type: 'char'
          description: 'gender from amber data'
        - field: 'gender_cobalt'
          type: 'char'
          description: 'gender from cobalt data'
        - field: 'deleted_genes'
          type: 'int'
          description: 'number of genes with cn < 0.5'
        - field: 'contamination'
          type: 'float'
          description:
            'rate of contamination in tumor sample as determined by Amber'
        - field: 'germline_aberrations'
          type: 'char'
          description:
            'any germline chromosomal aberrations detected (KLINEFELTER,
            TRISOMY_X, TRISOMY_21, TRISOMY_13, TRISOMY_18, TRISOMY_15, XYY,
            MOSAIC_X)'
        - field: 'mean_depth_amber'
          type: 'float'
          description: 'as calculated by Amber'
        - field: 'loh_percent'
          type: 'float'
          description: 'LOH percentage'
  somclonality:
    description: 'Clonality peak model data.'
    schema:
      latest:
        - field: 'peak'
          type: 'float'
          description: 'peak'
        - field: 'bucket'
          type: 'float'
          description: 'bucket'
        - field: 'bucket_weight'
          type: 'float'
          description: 'bucket weight'
        - field: 'peak_avg_weight'
          type: 'float'
          description: 'peak average weight'
        - field: 'is_valid'
          type: 'char'
          description: 'is valid'
        - field: 'is_subclonal'
          type: 'char'
          description: 'is subclonal'
  somhist:
    description: 'Somatic variant histogram data.'
    schema:
      latest:
        - field: 'variant_cn_bucket'
          type: 'float'
          description: 'variant cn bucket'
        - field: 'cn_bucket'
          type: 'float'
          description: 'cn bucket'
        - field: 'count'
          type: 'float'
          description: 'count'
