cuppa_cancer_types <- tibble::tribble(
  ~raw                                 , ~tidy                                 ,
  "Acute myeloid leukemia"             , "acute_myeloid_leukemia"              ,
  "Anogenital"                         , "anogenital"                          ,
  "Bile duct/Gallbladder"              , "bile_duct_gallbladder"               ,
  "Bone/Soft tissue: Other"            , "bone_soft_tissue_other"              ,
  "Breast"                             , "breast"                              ,
  "Cartilaginous neoplasm"             , "cartilaginous_neoplasm"              ,
  "Colorectum/Appendix/SmallIntestine" , "colorectum_appendix_small_intestine" ,
  "Esophagus/Stomach"                  , "esophagus_stomach"                   ,
  "GIST"                               , "gist"                                ,
  "Glioma"                             , "glioma"                              ,
  "Head and neck: other"               , "head_and_neck_other"                 ,
  "Kidney"                             , "kidney"                              ,
  "Kidney-ChRCC"                       , "kidney_chrcc"                        ,
  "Leiomyosarcoma"                     , "leiomyosarcoma"                      ,
  "Liposarcoma"                        , "liposarcoma"                         ,
  "Liver"                              , "liver"                               ,
  "Lung: NET"                          , "lung_net"                            ,
  "Lung: Non-small Cell"               , "lung_nonsmallcell"                   ,
  "Lung: Small Cell"                   , "lung_smallcell"                      ,
  "Lymphoid tissue"                    , "lymphoid_tissue"                     ,
  "Medulloblastoma"                    , "medulloblastoma"                     ,
  "Melanoma"                           , "melanoma"                            ,
  "Mesothelium"                        , "mesothelium"                         ,
  "Myeloproliferative neoplasm"        , "myeloproliferative_neoplasm"         ,
  "Osteosarcoma"                       , "osteosarcoma"                        ,
  "Ovary/Fallopian tube"               , "ovary_fallopian_tube"                ,
  "Pancreas"                           , "pancreas"                            ,
  "Pancreas: NET"                      , "pancreas_net"                        ,
  "Pilocytic astrocytoma"              , "pilocytic_astrocytoma"               ,
  "Prostate"                           , "prostate"                            ,
  "Salivary gland/Adenoid cystic"      , "salivary_gland_adenoid_cystic"       ,
  "Skin: Other"                        , "skin_other"                          ,
  "Small intestine/Colorectum: NET"    , "small_intestine_colorectum_net"      ,
  "Thyroid gland"                      , "thyroid_gland"                       ,
  "Urothelial tract"                   , "urothelial_tract"                    ,
  "Uterus: Endometrium"                , "uterus_endometrium"
)
